class Hotel {
  final String name,
      image,
      classification,
      address,
      ph1,
      ph2,
      ph3,
      email1,
      email2,
      website,
      overview,
      facilities;
      double latitude, longitude;

  Hotel({
    required this.name,
    required this.image,
    this.classification ="",
    required this.address,
    required this.ph1,
    this.ph2 = "",
    this.ph3 = "",
    required this.email1,
    this.email2 = "",
    this.website = "",
    this.overview="",
    required this.facilities,
    required this.latitude ,
    required this.longitude ,
  });
}

List<Hotel>hotel= [
  Hotel(
    name: "Coconut Lagoon",
    image: "assets/stay/ho-coconut.jpg",
    classification: "Heritage",
    address: "Kumarakom, Kottayam, Pin: 686563",
    ph1: "+914812528200",
    ph2: "+914844261711",
    ph3: "",
    email1: "coconutlagoon@cghearth.com",
    email2: "contact@cghearth.com",
    website: "http://www.cghearth.com/coconut-lagoon",
    overview: "An interplay of coconut groves and backwater canals, with old wooden Kerala homes transplanted, preserved and cherished. Coconut Lagoon is located in a sheltered and enchanting cove in Kumarakom. This resort reflects the diversity and magnificence of Vemband lake. It is a CGH Earth experience that respects the rich but delicate ecosphere and the vibrant culture of Kuttanad region, where old agrarian homes are reconstituted to offer you an entry into a charming world following the gentle pulse of the backwaters.",
    facilities: "Restaurant, Ayurveda Center, Fitness Center, Internet facility, Souvenir Shop, Swimming Pool, Wi-fi Lobby",
    latitude:9.632874,
    longitude:76.418639,
  ),
  Hotel(
    name: "Vijaya Park",
    image: "assets/stay/ho-vijaya.jpg",
    classification: "4 Star",
    address: "Kothanaloor, Kottayam, Pin: 686603",
    ph1: "+914829243546",
    ph2: "+914829243547",
    ph3: "+914829243550",
    email1: "vijayapark@gmail.com",
    email2: "info@vijayapark.com",
    website: "http://www.vijayapark.com",
    overview: "Drive into Vijaya Park while you are on your way to get yourself refreshed. Vijaya Park is not just a hotel or way-side inn. It is more than a star hotel you see around. Vijaya Park is half way in between Ernakulam and Kottayam at Kothanallor. Situated along the highway, Vijaya Park beckons you to stop by and enjoy its amenities that include excellent food, superbly furnished rooms and above all exclusive facilities for your private and corporate needs. Vijaya Park is a class by itself and it offers the most economic hospitality service in the district. Sprawling across acres of land fringed by unpolluted greenery, Vijaya Park is a gleaming white structure built with utmost care and finished with superb aesthetics.",
    facilities: "Parking, Restaurant, Locker, Air Conditioner, Television, Doctor on Call\n 24-hour Room Service, Banquet hall, , Coffee shop, Color TV, Conference hall, Hairdryer, Handicap Facilities, Iron / Ironing Board, Laundry, Non, Travel desk",
    latitude:9.721112,
    longitude:76.524323,
  ),
  Hotel(
    name: "Taj Kumarakom Resort & Spa",
    image: "assets/stay/ho-tajkumarakom.jpg",
    classification: "4 Star",
    address: "1/404, Kavanattinkara, Kumarakom,\nKottayam, Pin: 686566",
    ph1: "+914812525711",
    ph2: "+914812525716",
    ph3: "",
    email1: "noyal.jacob@tajhotels.com",
    email2: "arun.shenoy@tajhotels.com",
    website: "https://taj.tajhotels.com/en-in/taj-kumarakom-kerala",
    overview: "Uncover over a century of history and heritage at the Taj Kumarakom Resort & Spa this summer. The hotel’s community initiative program has taken the help of the local women from surrounding villages to light a thousand lamps, using its proceeds to support local communities. It’s your little contribution to them. Walk into the heart of nature while enjoying the unique sights and sounds of the lesser known regions of Kerala. Marvel at the carefully-lined coconut and banana plantations that make way for a sea of green in the form of green paddy fields. Indulge yourself with a variety of Indian and international cuisine available at our restaurants with the Breakfast Inclusive Rate.",
    facilities: "High speed Wi-fi, Parking, Restaurant, Bar, Locker, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, Ayurveda Center, Baby-sitting, Banquet hall, Boardroom, Boating facilities, Car hire service, Children's Play Area, Chinese dishes, Coffee Maker, Coffee shop, Conference hall, Conference hall, Credit Card Accepted, Cultural Programs, Currency exchange, DVD Player, Facsimile, Fitness Center, Flight status, Food, Gift Shop, Group Check-in, Hairdryer, Handicap Facilities, Homely Kerala Food, Indoor games, Internet facility, Laptop computers on hire, Laundry, Library, Lounge , Medical Tourism, Meet-and-Greet Services, MICE (Meetings, Incentives, Conferences & Events), Mini , North Indian Dishes, Online reservation, Photocopying, Private party area, , Scanning services, Shopping Arcade/ Boutiques, South Indian Dishes, Souvenir Shop, Spa, Swimming Pool, Tour Packages, Transport and Guide Services, Travel desk, Vending Machine, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp, Workstations, Yoga Centre",
    latitude:9.626274,
    longitude:76.426483,
  ),
  Hotel(
    name: "Hotel Excalibur",
    image: "assets/stay/ho-excalibur.jpg",
    classification: "4 Star",
    address: "Caritas Junction, Thellakom\nKottayam, Pin: 686016",
    ph1: "+918281234007",
    ph2: "+914812791781",
    ph3: "+914812791783",
    email1: "info@hotelexcalibur.in",
    email2: "",
    website: "www.hotelexcalibur.in",
    overview: "This 4 star business class hotel is ideally located at Ettumanoor, a lovely place with beautiful landscape, lush green vegetation and pristine atmosphere, just minutes away from Kottayam. Exacalibur offers the perfect vacation getaway for city dwellers, trying to break free from daily mundane routine. Business or leisure, its wide range of accommodation makes it a suitable destination for all type of travelers. There are places of worship, shopping centres and various other business establishments within walking distance. Internationally renowned tourist attractions like the backwaters of Kumarakom and the enchanting hill stations of Wagamon are only a few miles away. The magnificent décor, vibrant location and opulence make one’s stay in hotel Exacalibur something very special indeed.",
    facilities: "Parking, Restaurant, Air Conditioner, Television, Doctor on Call, Coffee Maker, Coffee shop, Color TV, Conference hall, Hairdryer, Handicap Facilities, Internet facility, Iron / Ironing Board, Laundry, Travel desk, Wi-fi Lobby ",
    latitude:9.647515,
    longitude:76.548522,
  ),
  Hotel(
    name: "Hotel Laya Pvt. Ltd.",
    image: "assets/stay/ho-laya.jpeg",
    classification: "4 star",
    address: "Main Road, Athirampuzha\nKottayam, Pin: 686562",
    ph1: "+918281871244",
    ph2: "+914812732300",
    ph3: "+914812732299",
    email1: "hotel.laya@gmail.com",
    email2: "hotel,laya@gmail.com",
    website: "www.hotellaya.com",
    overview: "",
    facilities: "High speed Wi-fi, Parking, Restaurant, Bar, Locker, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, Baby-sitting, Banquet hall, Boardroom, Boating facilities, , Chinese dishes, Coffee Maker, Coffee shop, Color TV, Conference hall, Conference hall, Credit Card Accepted, DVD Player, Food, Group Check-in, Hairdryer, Handicap Facilities, Homely Kerala Food, In Room Safe, Internet facility, Iron / Ironing Board, Laptop computers on hire, Laundry, Lounge , MICE (Meetings, Incentives, Conferences & Events), Mini , Non , North Indian Dishes, Online reservation, Refrigerator, , South Indian Dishes, Tour Packages, Transport and Guide Services, Travel desk, Wi-fi Lobby, Work Desk with Lamp",
    latitude:9.667249,
    longitude:76.532972,
  ),
  Hotel(
    name: "Armani Residency",
    image: "assets/stay/ho-armani.jpg",
    classification: "4 Star",
    address: "Ramapuram - Koothattukulam Road\nPala, Kottayam, Pin: 686576",
    ph1: "+919188643360",
    ph2: "+914822263360",
    ph3: "",
    email1: "armaniresidency@gmail.com",
    email2: "",
    website: "www.armaniresidency.com",
    overview: "Hotel Armani Residency, located in the calm environs of Ramapuram near Pala (Kottayam) continues to attract tourists through its enchanting presence and its hospitality services. In the hotel we have strived to amalgamate the best concepts of hospitality, hotel keeping, and guest management, and worked hard to make it work. We have directed our efforts towards making it one of the best accommodations in Kerala. Whether you are a business visitor in search of a quality and affordable overnight stay, or a tourist looking for a decent and affordable accommodation, or a diner in search of good food, you can seek our individual attention at all times. Located in the tranquil and eco-friendly surroundings of Ramapuram, it offers lots of personal space for people who wish to seek relaxation and replenish their positive energies here.",
    facilities: "High speed Wi-fi, Bar, Locker, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, Baby-sitting, Banquet hall, Boardroom, Car hire service, Chinese dishes, Coffee Maker, Coffee shop, Color TV, Conference hall, Conference hall, Credit Card Accepted, Currency exchange, Facsimile, Food, Group Check-in, Hairdryer, In Room Safe, Internet facility, Iron / Ironing Board, Laptop computers on hire, Library, Lounge , Medical Tourism, Meet-and-Greet Services, Mini , Non , North Indian Dishes, Online reservation, Photocopying, Refrigerator, Scanning services, South Indian Dishes, Spa, Tour Packages, Translation / interpretation services (on request), Transport and Guide Services, Travel desk, Vending Machine, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp, Workstations, Yoga Centre",
    latitude:9.800291,
    longitude:76.657647,
  ),
  Hotel(
    name: "Hotel Floral Park",
    image: "assets/stay/ho-floral.jpg",
    classification: "4 Star",
    address: "Near Medical College\nGandhinagar P. O., Kottayam, Pin: 686008",
    ph1: "+919387659039",
    ph2: "+918281373811",
    ph3: "+914812597020",
    email1: "info@hotelfloralpark.in",
    email2: "",
    website: "http://hotelfloralpark.in",
    overview: "Hotel Floral park is a combination of traditional charm and modern convenience. A four star facility business class hotel, it is situated near Govt. Medical college Kottayam. Every amenity and facility that assures guests for a pleasant stay can be availed here. We dedicate our efforts to maintain world class standards while constantly providing personal service without interrupting your privacy. 19 Rooms including suites with all modern conveniences make up the accommodation. Check out time 24 hours. In short, a place of peace and relaxation in the heart of Kottayam.",
    facilities: "Parking, Restaurant, Bar Locker, Air Conditioner, Television, Doctor on Call, Banquet hall, Coffee shop, Color TV, Conference hall, Fitness Center, Hairdryer, Handicap Facilities, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, Travel desk",
    latitude:9.632952,
    longitude:76.523487,
  ),
  Hotel(
    name: "Green Fields",
    image: "assets/stay/ho-greenfields.jpg",
    classification: "4 Star",
    address: "Kaippuzamuttu, Cheepungal P. O.\nKumarakom, Kottayam, Pin: 686563",
    ph1: "+919388356875",
    ph2: "+914812523222",
    ph3: "+914812523444",
    email1: "mail@greenfieldskumarakom.in",
    email2: "rm@greenfieldskumarakom.in",
    website: "www.greenfieldskumarakom.in",
    overview: "Green Fields sprawls across tastefully landscaped environs in the hamlet of Kumarakom.\nIt is perhaps the only place of its kind in the sleepy village. Surrounded by lush green paddy fields, the resort offers proximity to the famous Vembanad lake and bird sanctuary among many other nearby places of interest to choose from. Our choices of opulent en-suite living spaces include superior rooms, deluxe rooms and suite rooms that are grandiosely yet tastefully appointed. Extra-large double beds, roomy built-in wardrobes, concealed refrigerator, princely bathrooms that pamper your every need, wall-mounted flat-screen cable TVs and private balconies are standard features.",
    facilities: " High speed Wi-fi, Parking, Restaurant, Bar, Locker, Air Conditioner, Television, Doctor on Call,Ayurveda Center, Banquet hall, Boardroom, Boating facilities, Car hire service, Children's Play Area, Chinese dishes, Coffee Maker, Coffee shop, Color TV, Conference hall, Conference hall, Credit Card Accepted, Cultural Programs, Currency exchange, Fitness Center, Flight status, Food, Gift Shop, Group Check-in, Hairdryer, Handicap Facilities, Homely Kerala Food, In Room Safe, Indoor games, Internet facility, Iron / Ironing Board, Laundry, Medical Tourism, Meet-and-Greet Services, MICE (Meetings, Incentives, Conferences & Events), Mini , North Indian Dishes, Online reservation, Photocopying, Private party area, Refrigerator, , Secretarial services, South Indian Dishes, Swimming Pool, Tour Packages, Transport and Guide Services, Travel desk, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp, Workstations, Yoga Centre",
    latitude:9.645770,
    longitude:76.430277,
  ),
  Hotel(
    name: "Hotel Indraprastha",
    image: "assets/stay/ho-indraprastha.jpg",
    classification: "4 Star",
    address: "S H Mount P. O., M. C. Road,\nKottayam, Pin: 686006",
    ph1: "+919496001642",
    ph2: "+919496001649",
    ph3: "+914812569256",
    email1: "info@indraprasthaktm.com",
    email2: "gm@indraprasthaktm.com",
    website: "www.indraprasthaktm.com",
    overview: "Hotel Indraprastha Kottayam is a 4-star hotel strategically located in the heart of Kottayam city's dynamic business, cultural and entertainment hubs. It is ideal for both business and leisure travellers looking for value for money accommodation in Kottayam.",
    facilities: "High speed Wi-fi, Parking, Restaurant,Bar, Locker,  Air Conditioner,  Television,  Doctor on Call,Banquet hall, Boardroom, Boating facilities, Car hire service, Chinese dishes, Coffee Maker, Coffee shop, Color TV, Conference hall, Conference hall, Credit Card Accepted, Currency exchange, Fitness Center, Flight status, Florist, Food, Gift Shop, Group Check-in, Hairdryer, Handicap Facilities, Homely Kerala Food, In Room Safe, Internet facility, Laundry, Lounge , Meet-and-Greet Services, Mini , North Indian Dishes, Online reservation, Photocopying, Private party area, Refrigerator, , South Indian Dishes, Swimming Pool, Tour Packages, Translation / interpretation services (on request), Transport and Guide Services, Travel desk, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp, Workstations",
    latitude:9.601300,
    longitude:76.532100,
  ),
  Hotel(
    name: "Castle Residency",
    image: "assets/stay/ho-castle.jpg",
    classification: "4 Star",
    address: "Peruva, Kottayam\nPin: 686610",
    ph1: "+919846265425",
    ph2: "+914829251407",
    ph3: "",
    email1: "castleresidency@gmail.com",
    email2: "",
    website: "http://www.castleresidency.com",
    overview: "Hotel Castle Residency is a bright and spacious hotel that combines comfort and style with a touch of luxury. The building itself is a landmark in Peruva. Castle Residency is a contemporary Kerala style four star hotel made on sloping roofs, granite and rosewood-teakwood work combinations that combines excellent facilities for conferences, meetings and events with a very accessible location. Our location ideally positions us for a wide variety of activities both at the hotel and at local amenities and tourist attractions.",
    facilities: "Parking, Restaurant, Bar, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, Banquet hall, , Coffee Maker, Coffee shop, Color TV, Conference hall, Fitness Center, Gift Shop, Internet facility, Mini , Refrigerator, Secretarial services, Travel desk, Wi-fi Lobby",
    latitude:9.822824,
    longitude:76.502243,
  ),
  Hotel(
    name: "White Gate Residency",
    image: "assets/stay/ho-whitegate.jpg",
    classification: "4 Star",
    address: "2/297A, Valiyakavala, Vaikom,\nKottayam, Pin: 686141",
    ph1: "+919895104666",
    ph2: "+914829216961",
    ph3: "+914829216965",
    email1: "sales@whitegateresidency.com",
    email2: "info@whitegateresidency.com",
    website: "http://whitegateresidency.com",
    overview: "Welcome to White Gate, Vaikom, the one n' only 4 star business hotel in Vaikom, the pristine land where peace and history lies hand in hand. Conceived as the ideal retreat for the leisure or business traveller, our hotel offers you a stay in the heart of this backwater town, enjoying the comfort of personalized service and well-equipped modern amenities. The aesthetic ambience, well-appointed guest rooms, and food specially prepared to suit each palate, are bound to have their soothing effect on the most travel-weary soul. The lavishly proportioned rooms at The White Gate have been contoured to provide an ambience that soothes and refreshes. Elegantly fitted with every requisite for a luxurious stay, our rooms reflect opulent refinement at its very best.",
    facilities: "High speed Wi-fi, Parking, Restaurant, Bar, Locker, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, Baby-sitting, Banquet hall, Beauty saloon, Boardroom, Boating facilities, Car hire service, Chinese dishes, Coffee Maker, Coffee shop, Color TV, Conference hall, Credit Card Accepted, Currency exchange, Exhibition hall, Fitness Center, Food, Gift Shop, Group Check-in, Hairdryer, Handicap Facilities, In Room Safe, Internet facility, Iron / Ironing Board, Laptop computers on hire, Laundry, Medical Tourism, Meet-and-Greet Services, MICE (Meetings, Incentives, Conferences & Events), Mini , North Indian Dishes, Online reservation, Photocopying, Refrigerator, , Scanning services, South Indian Dishes, Travel desk, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp",
    latitude:9.758118,
    longitude:76.398774,
  ),
  Hotel(
    name: "Hotel Aida",
    image: "assets/stay/ho-aida.jpg",
    classification: "3 Star",
    address: "Aida Junction, M. C. Road\nKottayam Pin: 686001",
    ph1: "+914812568391",
    ph2: "+914812568392",
    ph3: "",
    email1: "bookings@hotelaida.in",
    email2: "hotelaidaktm@gmail.com",
    website: "http://www.hotelaida.in",
    overview: "Hotel Aida assures great experience to its customers. Keeping up with changing scenario in the hotel business was never easy but with great determination and hard work, we have achieved great success in the business. Over the decades, Hotel Aida has established a reputation for excellence. Well-trained staff and quality service have been essential in gaining a wide list of loyal customers in the long run. The goodwill of Hotel Aida is a result of the commitment and dedication of the highly motivated staff and management. Setting high standards for the hotels in Kottayam to match up to and provide a world-class experience to our customers remains our motto. Hotel Aida is ideally located at Aida Junction on M. C. Road in Kottayam town and offers a perfect combination of lodging, dining and meeting facilities. The hotel features 35 guest rooms, 4 banquet halls, a splendid 160-seater multicuisine restaurant and a classic pub.",
    facilities: "Restaurant, Bar, Locker, 24-hour Room Service, Coffee Maker, Conference hall, Hairdryer, Internet facility, Iron / Ironing Board, Laundry, Mini",
    latitude:9.582776,
    longitude:76.521647,
  ),
  Hotel(
    name: "Hotel Icon Classic",
    image: "assets/stay/ho-icon.jpg",
    classification: "3 Star",
    address: "Near Old Press Club, M. C. Road\nThirunakkara, Kottayam, Pin: 686001",
    ph1: "+918111800999",
    ph2: "+919544544848",
    ph3: "+914812568012",
    email1: "hoteliconclassic@gmail.com",
    email2: "",
    website: "http://www.iconclassic.com",
    overview: "Icon Classic is the finest hotel you can find at the heart of Kottayam with all designed with customer in our mind. Icon Classic is designed with the royal blend and iconic style in every nook and corner. We have connectivity to all the major tourist destinations around Kottayam. We at Icon Classic believe in providing the best care and services for our clients, so that their stay is hassle-free, pleasant and memorable. There are 11 well furnished air conditioned superior rooms and 1 luxurious suite & 1 guest room for differently-abled guests. We provide 24hrs room service.",
    facilities: "Parking, Restaurant,Bar, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, , Coffee Maker, Color TV, Hairdryer, Handicap Facilities, Internet facility, Iron / Ironing Board, Laundry, Refrigerator, Secretarial services, Travel desk, Wi-fi Lobby",
    latitude:9.589242,
    longitude:76.521542,
  ),
  Hotel(
    name: "Hotel Breeze Land",
    image: "assets/stay/ho-breezeland.jpg",
    classification: "3 Star",
    address: "By-Pass Junction, Vazhappally\nM. C. Road, Changanacherry\nKottayam Pin: 686103",
    ph1: "+919447753711",
    ph2: "+919446523701",
    ph3: "+914812412701",
    email1: "hotelbreezeland@gmail.com",
    email2: "",
    website: "www.hotelbreezeland.com",
    overview: "Hotel Breeze Land at Changanacherry offers a unique ambiance adorned with modern architecture, superior comfort and unmatched service; all of which makes it a truly distinctive hotel in its class. May it be a pleasure trip or a business trip, Hotel Breeze Land is a definite choice of many, no matter what the occasion may be. It is indeed a wonderful place to start and end a day in God’s Own Country! Hotel Breeze Land offers 16 guest rooms tucked up with elegant furnishings and modern amenities. Dining options are next to unlimited as Hotel Breeze Land includes three restaurants where you can treat your taste buds to some of the finest multi cuisines available in Kerala. The warm and cozy vibe prevalent in every corner of the Breeze Land hotel is really refreshing, and makes you feel at home.",
    facilities: "High speed Wi-fi, Parking, Restaurant, Bar, Air Conditioner, Television, Banquet hall, Boardroom, , Chinese dishes, Coffee shop, Color TV, Conference hall, Currency exchange, Food, Group Check-in, Hairdryer, Homely Kerala Food, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, Online reservation, Refrigerator, South Indian Dishes, Travel desk, Wi-fi Lobby",
    latitude:9.466158,
    longitude:76.530788,
  ),
  Hotel(
    name: "Back Water Ripples",
    image: "assets/stay/ho-backwater.jpg",
    classification: "3 Star",
    address: "Kumarakom, Kottayam\nPin: 686563",
    ph1: "+919447812345",
    ph2: "+914812523600",
    ph3: "",
    email1: "mail@backwaterripples.com",
    email2: "",
    website: "www.backwaterripples.com",
    overview: "",
    facilities: "High speed Wi-fi, Parking, Restaurant, Bar, Locker, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, Ayurveda Center, Baby-sitting, Banquet hall, Beauty saloon, Boardroom, Boating facilities, Car hire service, Children's Play Area, Chinese dishes, Coffee Maker, Coffee shop, Color TV, Conference hall, Conference hall, Credit Card Accepted, Cultural Programs, Currency exchange, Exhibition hall, Facsimile, Fitness Center, Florist, Food, Gift Shop, Group Check-in, Hairdryer, Handicap Facilities, Homely Kerala Food, In Room Safe, Indoor games, Internet facility, Iron / Ironing Board, Laundry, Library, Lounge , Medical Tourism, Meet-and-Greet Services, MICE (Meetings, Incentives, Conferences & Events), Mini , North Indian Dishes, Online reservation, Refrigerator, , Scanning services, Shopping Arcade/ Boutiques, South Indian Dishes, Souvenir Shop, Spa, Swimming Pool, Tour Packages, Translation / interpretation services (on request), Transport and Guide Services, Travel desk, Video-conferencing facilities & Web casting facilities, Weddings in Kerala, Work Desk with Lamp, Yoga Centre",
    latitude:9.588791,
    longitude:76.424311,
  ),
  Hotel(
    name: "Hotel Elegance",
    image: "assets/stay/ho-elegance.jpg",
    classification: "3 Star",
    address: "Highway Road, Kidangoor\nKottayam, Kottayam, Pin: 686572",
    ph1: "+919497202758",
    ph2: "+914822254398",
    ph3: "+914822257398",
    email1: "mailktm@thehotelelegance.com",
    email2: "",
    website: "www.thehotelelegance.com",
    overview: "best 3 star hotel , nice staying area, low prices rooms",
    facilities: "High speed Wi-fi, Parking, Restaurant, Bar, Locker, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, Baby-sitting, Banquet hall, Boardroom, , Chinese dishes, Coffee shop, Conference hall, Conference hall, Credit Card Accepted, Exhibition hall, Food, Gift Shop, Group Check-in, Hairdryer, Handicap Facilities, Homely Kerala Food, Internet facility, Laundry, Lounge , MICE (Meetings, Incentives, Conferences & Events), Mini , Non , North Indian Dishes, Online reservation, Photocopying, , Shopping Arcade/ Boutiques, South Indian Dishes, Travel desk, Wi-fi Lobby",
    latitude:9.682875,
    longitude:76.609600,
  ),
  Hotel(
    name: "Abad Hotels & Resorts",
    image: "assets/stay/ho-abad.jpg",
    classification: "",
    address: "New Nazarath Road, Konchumada\nKumarakom, Kottayam\nPin: 686563",
    ph1: "+914812523819",
    ph2: "+914844144000 ",
    ph3: "+914842381122",
    email1: "reservations@abdhotels.com",
    email2: "",
    website: "https://www.abadhotels.com/lakeresort",
    overview: "Abad Whispering Palms is located at Kumarakom, the most exotic destination in Kerala right on the banks of the Vembanadu lake. The resort offers 53 elegantly designed garden and lake facing suites and cottages, bamboo villas – three villas with private pool.",
    facilities: "High speed Wi-fi, Parking, Restaurant, Bar, Air Conditioner, Television, Doctor on Call,Ayurveda Center, Baby-sitting, Banquet hall, Boating facilities, , Children's Play Area, Chinese dishes, Coffee Maker, Coffee shop, Color TV, Conference hall, Conference hall, Credit Card Accepted, Cultural Programs, Currency exchange, Exhibition hall, Food, Gift Shop, Group Check-in, Hairdryer, Handicap Facilities, Homely Kerala Food, Indoor games, Internet facility, Laundry, Library, Mini , North Indian Dishes, Online reservation, Photocopying, Refrigerator, , Scanning services, South Indian Dishes, Spa, Swimming Pool, Tour Packages, Translation / interpretation services (on request), Transport and Guide Services, Travel desk, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp",
    latitude:9.576470,
    longitude:76.422234,
  ),
    Hotel(
    name: "Aquarius Hotel",
    image: "assets/stay/ho-aquarius.jpg",
    classification: "",
    address: "Kacherikavala, Vaikom,\nKottayam, Pin: 686141",
    ph1: "+914829231727",
    ph2: "",
    ph3: "",
    email1: "info@aquariushotel.in",
    email2: "",
    website: "www.aquariushotel.in",
    overview: "",
    facilities: "High speed Wi-fi, Parking, Restaurant, Bar, Air Conditioner, Television, Doctor on Call,Banquet hall, Boardroom, Car hire service, Color TV, Conference hall, Credit Card Accepted, Food, Group Check-in, Hairdryer, Internet facility, Laundry, Lounge , Mini , Non , North Indian Dishes, Online reservation, , South Indian Dishes, Travel desk, Work Desk with Lamp",
    latitude:9.750278,
    longitude:76.392672,
  ),
     Hotel(
    name: "Backwater Ripples Pvt. Ltd.",
    image: "assets/stay/ho-backwater-pvt.jpg",
    classification: "",
    address: "Nazerath Church Road\nKumarakom, Kottayam, Pin: 686563",
    ph1: "+919447756700",
    ph2: "+919446015404",
    ph3: "+914812523600",
    email1: "mail@backwaterripples.com",
    email2: "",
    website: "www.backwaterripples.com",
    overview: "Backwater Ripples, a Kerala themed resort which is spread on 10 acres of lush green land with inland waterways at Kumarakom is directly overlooking the Vembanad Lake, shimmering sapphire expanse, sprawling far and wide. Backwater Ripples is a dreamy & tranquil holiday destination, where you can have spellbinding encounters with nature. We offer 34 rooms in various choices of accommodations. Relish a psychedelic sunset on a montage of clouds, carrying the day’s catch of pearl spot & jumbo prawns or the flying flurry of evening birds, or just relax and enjoy the cool afternoon breeze.",
    facilities: "Parking, Restaurant,Television, Doctor on Call,24-hour Room Service, Ayurveda Center, Banquet hall, Car hire service, Children's Play Area, Coffee Maker, Color TV, Fitness Center, Hairdryer, In Room Safe, Indoor games, Refrigerator, Swimming Pool, Travel desk",
    latitude:9.588795,
    longitude:76.424311,
  ),
     Hotel(
    name: "Chrysoberyl Hotel & Convention Centre",
    image: "assets/stay/ho-chrysoberyl.jpg",
    classification: "",
    address: "K. K. Road, Collectorate P. O.\nKanjikuzhi, Kottayam, Pin: 686002",
    ph1: "+919495587000",
    ph2: "+914812587000",
    ph3: "+914812587020",
    email1: "info@thechrysoberyl.com",
    email2: "",
    website: "www.thechrysoberyl.com",
    overview: "With years of experience in hospitality business, Chrysoberyl management is always keen about delivering the best to our customers. Our aim is to provide maximum comfort to our guests and their satisfaction is of utmost importance for us. We believe in service with perfection and commitment. Chryoberyl has a total of 42 rooms belonging to a variety of categories, designed for luxury and comfort. The interiors are designed and arranged in such a way that our guests can feel at home and relax while at the same time enjoy the luxury.",
    facilities: " Parking, Restaurant, Television, Doctor on Call,Beauty saloon, , Color TV, Fitness Center, Hairdryer, Handicap Facilities, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, Spa, Swimming Pool, Travel desk, Wi-fi Lobby",
    latitude:9.588528,
    longitude:76.536297,
  ),
       Hotel(
    name: "Club Mahindra Kumarakom",
    image: "assets/stay/ho-clubmahindra.jpg",
    classification: "",
    address: "Near Chakrampady Bus Stand\nKumarakom North, Kottayam\nPin: 686563",
    ph1: "+918943334140",
    ph2: "+914812525826",
    ph3: "+914812525638",
    email1: "manikandan.mp@mahindraholidays.com",
    email2: "fo.kumarakom@mahindraholidays.com",
    website: "www.clubmahindra.com",
    overview: "",
    facilities: " Parking, Restaurant, Television, Children's Play Area, Color TV, Internet facility, Laundry, Souvenir Shop, Spa, Swimming Pool, Travel desk, Wi-fi Lobby",
    latitude:9.618700,
    longitude:76.438800,
  ),
       Hotel(
    name: "Dubai Hotel",
    image: "assets/stay/ho-dubai.jpg",
    classification: "",
    address: "Opposite St. Johns Attamangalam Church\nKumarakom, Kottayam, Pin: 686563",
    ph1: "+919447052582",
    ph2: "+914812525821",
    ph3: "+914812525150",
    email1: "dubaihotelkumarakom@gmail.com",
    email2: "dubaihotelkumarakom@hotmail.com",
    website: "www.dubaihotelkumarakom.com",
    overview: "Situated in Kumarakom, this hotel is within 2 miles (3 km) of Kumarakom Boat Jettyand Vembanad Lake. Kumarakom Bird Sanctuary and Kottayam Cheriyapally are also within 6 miles (10 km). This hotel features 2 restaurants, spa services and 24-hour room service. Free Wi-Fi in public areas and free self parking are also provided. Additionally, laundry facilities, a 24-hour front desk and express check-in are on-site. All 15 rooms offer TVs with cable channels. Free bottled water, ceiling fans and safes are among the other amenities that guests will find.",
    facilities: "  High speed Wi-fi, Parking  Restaurant, Air Conditioner, Television,  Doctor on Call,24-hour Room Service, Boating facilities, Car hire service, Chinese dishes, Coffee shop, Color TV, Credit Card Accepted, Food, Homely Kerala Food, Non , North Indian Dishes, Online reservation, South Indian Dishes",
    latitude:9.592200,
    longitude:76.441100,
  ),
    Hotel(
    name: "Eastend Lakesong",
    image: "assets/stay/ho-eastend.jpg",
    classification: "",
    address: "Ammankari Road, Kumarakom,\nKottayam, Pin: 686563",
    ph1: "+919446001498",
    ph2: "+914812526300",
    ph3: "",
    email1: "crs@eastend.in",
    email2: "marketing@eastend.in",
    website: "www.eastend.in",
    overview: "Located at the bank of Vembanadu Lake and offers the longest backwater frontage of 200 meters. The most ideal resort for leisure as well as MICE. 68 well appointed rooms , conference hall which can accommodate 500 pax , ayurveda centre and other amenities make this resort the first choice of travelling class.",
    facilities: " High speed Wi-fi, Parking, Restaurant, Bar, Locker,  Air Conditioner,  Television,  Doctor on Call,Ayurveda Center, Banquet hall, Boardroom, Boating facilities, Car hire service, Children's Play Area, Chinese dishes, Coffee Maker, Coffee shop, Color TV, Conference hall, Conference hall, Credit Card Accepted, Currency exchange, Facsimile, Fitness Center, Food, Gift Shop, Group Check-in, Hairdryer, Handicap Facilities, In Room Safe, Indoor games, Internet facility, Iron / Ironing Board, Laundry, Library, MICE (Meetings, Incentives, Conferences & Events), Mini , North Indian Dishes, Online reservation, Photocopying, Private party area, Refrigerator, , Scanning services, South Indian Dishes, Souvenir Shop, Swimming Pool, Tour Packages, Transport and Guide Services, Travel desk, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp, Yoga Centre",
    latitude:9.594298,
    longitude:76.425950,
  ),
  Hotel(
    name: "Finch Hotels",
    image: "assets/stay/ho-finch.jpg",
    classification: "",
    address: "Errattupetta, Pala\n Kottayam, Pin: 686122",
    ph1: "+914822275979",
    ph2: "+914822275980",
    ph3: "",
    email1: "sales@finchhotel.com",
    email2: "",
    website: "www.finchhotel.com",
    overview: "",
    facilities: " High speed Wi-fi,  Parking,  Restaurant,  Bar,  Air Conditioner,  Television,24-hour Room Service, Baby-sitting, Banquet hall, Boardroom, , Chinese dishes, Coffee Maker, Coffee shop, Color TV, Conference hall, Conference hall, Credit Card Accepted, Exhibition hall, Food, Gift Shop, Hairdryer, Handicap Facilities, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, Mini , North Indian Dishes, Online reservation, South Indian Dishes, Travel desk, Wi-fi Lobby",
    latitude:9.688485,
    longitude:76.775736,
  ),
  Hotel(
    name: "Hotel Arcadia",
    image: "assets/stay/ho-arcadia.jpg",
    classification: "",
    address: "Opp. KSRTC Bus Station\nT. B. Road, Kottayam, Pin: 686001",
    ph1: "+919961994499",
    ph2: "+914812569999",
    ph3: "",
    email1: "info@arcadiahotels.net",
    email2: "sales@arcadiahotels.net",
    website: "www.arcadiahotels.net",
    overview: "Hotel Arcadia, a fully equipped three star business hotel located in the heart of Kottayam provides you with a multitude of services that are sure to make your business and leisure trip an overwhelming experience. Over the decades, Hotel Arcadia has established a reputation for excellence. Well trained staff and quality service has been essential in gaining a wide list of loyal customers in the long run. The goodwill of Hotel Arcadia is a result of the commitment and dedication of the highly motivated staff and management. We have set high standards for the hotels in Kottayam to match up to and providing world class experience to our customers remains our motto. It’s one of the best hotels in Kottayam, ideally located on M C Road in Kottayam town- just opposite to KSRTC Bus stand and offers a perfect combination of lodging, dining and meeting facilities. Among the hotels in Kottayam, Hotel Arcadia stands out because of its passion for excellence and evolution.",
    facilities: " Parking, Bar, Air Conditioner,  Television,  Doctor on Call, Banquet hall, Boardroom, , Chinese dishes, Coffee Maker, Coffee shop, Color TV, Credit Card Accepted, Exhibition hall, Food, Group Check-in, Handicap Facilities, Internet facility, Laundry, Lounge , Online reservation, Private party area, Swimming Pool, Transport and Guide Services, Travel desk, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp",
    latitude:9.586113,
    longitude:76.522850,
  ),
  Hotel(
    name: "Hotel Mali International",
    image: "assets/stay/ho-mali.jpg",
    classification: "",
    address: "Near Railway Station\n Kottayam, Pin: 686001",
    ph1: "+919388758839",
    ph2: "+919388758837",
    ph3: "+914812580757",
    email1: "hotelmaliktm@gmail.com",
    email2: "malitoursandtravels@gmail.com",
    website: "www.hotelmali.com",
    overview: "Being situated adjacent to the Kottayam Railway Station, Mali International serves as a gateway to the tourist destinations and pilgrim centres of central Kerala. The nearest Airport is 85 Km away at Kochi. Be your motive divine, leisure or business, we will offer comfort in your way. A calm, serene place where you will find traditional Kerala hospitality at its best. Where you will re-energize yourself for your pursuits. Come to us, take home the experience you will never forget and make you long for coming back. We provide you utmost care & luxury so as to get the warmth of the cradle here.",
    facilities: " Parking,  Restaurant, Air Conditioner,  Television,  Doctor on Call, 24-hour Room Service, , Car hire service, Color TV, Conference hall, Internet facility, Tour Packages, Travel desk, Wi-fi Lobby",
    latitude:9.593492,
    longitude:76.531834,
  ),
  Hotel(
    name: "Hotel Olive International",
    image: "assets/stay/ho-olive.jpg",
    classification: "",
    address: "River View Road, Pala\nKottayam, Pin: 686575",
    ph1: "+914822211200",
    ph2: "+914822211300",
    ph3: "",
    email1: "info@hoteloliveinternational.com",
    email2: "",
    website: "www.hoteloliveinternational.com",
    overview: "The Hotel Olive International, a new address to hospitality industry, provides a guest with wide range of facilities to satisfy their entire travel needs. A bookshop is started with large collection of books in different languages including world classics, stories, articles, etc. We open an enormous range of rare and beautiful handicraft works to showcase Kerala’s incredible artistic culture and heritage. We are certain that our guests will enjoy and appreciate the beauty of these products showcased in our Curio shop – CURIOSITY. We facilitate an elegant and professional setting for signature conferences and social events for our guests. Treat your guests in a world-class hotel with every bit of modern luxury. Our experienced staff are there for all your enquiries and assist you at every turn.",
    facilities: "Parking, Restaurant, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, , Color TV, Conference hall, Currency exchange, Hairdryer, Handicap Facilities, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, Refrigerator, Travel desk, Wi-fi Lobby",
    latitude:9.711976,
    longitude:76.685464,
  ),
  Hotel(
    name: "Hotel Vettikattu Plaza",
    image: "assets/stay/ho-vettikattu.jpg",
    classification: "",
    address: "Neendoor, Kottayam",
    ph1: "+914812712648",
    ph2: "+914812712649",
    ph3: "",
    email1: "info@hotelvettikattuplaza.com",
    email2: "",
    website: "www.hotelvettikattuplaza.com",
    overview: "",
    facilities: "Parking, Restaurant, Bar, Locker, Air Conditioner, Doctor on Call, 24-hour Room Service, Banquet hall, Car hire service, Coffee Maker, Coffee shop, Conference hall, Currency exchange, Facsimile, Hairdryer, Handicap Facilities, Internet facility, Iron / Ironing Board, Laundry, Mini, Photocopying, Scanning services, Tour Packages, Travel desk, Wi-fi Lobby",
    latitude:9.685689,
    longitude:76.504982,
  ),
  Hotel(
    name: "Illikkalam Lakeside Cottages",
    image: "assets/stay/ho-illikkalam.jpg",
    classification: "",
    address: "New Nazareth Road, Kumarakom,\nKottayam, Pin: 686563",
    ph1: "+919447024234",
    ph2: "+919495735152",
    ph3: "+914812524234",
    email1: "klcottages@gmail.com",
    email2: "",
    website: "https://www.klcottages.com/",
    overview: "Relaxation … A… Unique Experience In The Lakeside Cottages At Kumarakom!!!\nILLIKKALAM Lakeside Cottages, Is The Only Property In Kumkarakom On The Side of Lake Vembanad,Owned And Managed In The Inherited Land, By The Kumarakom Native, is situated Just on the banks of Beautiful Lake Vembanad, at the best location of Kumarakom Village, Kottayam Dist, Kerala State, India. Cottages are located at banks of Lake Vembanad at Kumarakom, is an Eco friendly holiday property in one and a half acres of land and perfectly suitable for relaxation and holidaying for many days. The maximum breadth and length of the Vembanad lake, sun set and the moon set, comfortable breeze and the beautiful waves in the lake can be experienced from the cottages. We also Provide Houseboat,  Motorboat, Shikara & Speedboat Day Cruising. ",
    facilities: "High speed Wi-fi, Parking, Restaurant, Air Conditioner, Television, Doctor on Call, Boating facilities, Car hire service, Coffee shop, Color TV, Conference hall, Conference hall, Credit Card Accepted, Food, Group Check-in, Handicap Facilities, Homely Kerala Food, Indoor games, Internet facility, Laundry, MICE (Meetings, Incentives, Conferences & Events), Non , North Indian Dishes, Online reservation, Private party area, South Indian Dishes, Tour Packages, Transport and Guide Services, Travel desk, Weddings in Kerala, Wi-fi Lobby",
    latitude:9.584667,
    longitude:76.422221,
  ),
  Hotel(
    name: "Karma Chakra",
    image: "assets/stay/ho-karma.jpg",
    classification: "",
    address: "Near Nazreth Church, Kumarakom P. O.,\nKottayam, Pin: 686563",
    ph1: "+919446080121",
    ph2: "+914812526252",
    ph3: "+914812526253",
    email1: "chakra@karmagroup.com",
    email2: "",
    website: "https://karmagroup.com/find-destination/karma-retreats/karma-chakra/",
    overview: "Karma Chakra: Lake side Resort in Kerala nestles on the palm-fringed shores of Kerala’s largest lake called Lake Vembanad which covers 213 square Kms. This beautiful 24 room boutique resort provides the perfect hideaway from which to explore this rich and verdant region. All rooms have a view of the lake. Step on to your private balcony to drink in the sweeping views across the resort’s lush, sprawling gardens to the bustling lake and tropical landscape beyond. There’s a whole world of tranquil backwaters, alluring beaches and incredible wildlife out there, just waiting to be discovered. But there’s no rush. Take a dip in the infinity pool, feed your soul with an Ayurvedic massage or indulge in a signature cocktail before dinner.",
    facilities: "Parking, Restaurant, Bar, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, , Boating facilities, , Coffee Maker, Color TV, Fitness Center, Indoor games, Internet facility, Library, Spa, Swimming Pool, Travel desk",
    latitude:9.586992,
    longitude:76.423679,
  ),
  Hotel(
    name: "Kumarakom Lake Resort",
    image: "assets/stay/ho-kumarakomlake.jpg",
    classification: "",
    address: "Kumarakom North, Kottayam \nPin: 686563",
    ph1: "+914812524900",
    ph2: "",
    ph3: "",
    email1: "reservationklr@thepaul.in",
    email2: "",
    website: "www.kumarakomlakeresort.in",
    overview: "The rooms, villas and suites at Kumarakom Lake Resort are a perfect blend of Kerala's traditional architectural charm with luxurious, modern comforts. Each is a careful reconstruction of manas, the 16th century traditional homesteads of Kerala, with many such manas having been transplanted from their original locations and reassembled painstakingly by hand, plank by plank, tile by tile, to create the luxurious abodes at Kumarakom Lake Resort. The traditionally styled, luxuriously modern, open-roofed bathrooms set in small, aesthetically designed courtyards are a common feature to the villas and suites.",
    facilities: "Restaurant, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, Boating facilities, Color TV, Conference hall, Internet facility, Travel desk",
    latitude:9.612647,
    longitude:76.431224,
  ),
  Hotel(
    name: "Lakshmi Hotel & Resorts",
    image: "assets/stay/ho-lakshmi.jpg",
    classification: "",
    address: "Kumarakom North P.O., Kottayam \nPin: 686566",
    ph1: "+914812523313",
    ph2: "",
    ph3: "",
    email1: "mail@lakshmiresorts.com",
    email2: "info@lakshmiresorts.com",
    website: "www.lakshmiresorts.com",
    overview: "We carry forward the great tradition of hospitality through excellent holiday solutions. We provide total customer satisfaction and alongside generate employee satisfaction by providing congenial working environment. We contribute to the image of hospitality industry through our perfect service and high quality standards. Our ideal location Kumarakom intoxicates you with its charming exotica - seductive beaches, serene backwaters swaying coconut lagoons, lush green paddy fields, and delicious cuisine - a sublime heritage. You will feel the uniqueness the moment you step into our resort. We wish to share with you our life, our culture, and our home state Kerala. You are our royal guests. Welcome to Kerala, welcome to Lakshmi Resorts.",
    facilities: "Parking, Restaurant, Bar, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, Ayurveda Center, Banquet hall, , Car hire service, Color TV, Internet facility, Laundry, Non , Secretarial services, Tour Packages, Travel desk, Wi-fi Lobby",
    latitude:9.620184,
    longitude:76.430773,
  ),
  Hotel(
    name: "Marigold Hotel & Resort",
    image: "assets/stay/ho-marigold.jpg",
    classification: "",
    address: "Bypass Road Changanacherry\nKottayam, Pin: 686101",
    ph1: "+919495122276",
    ph2: "+914816999763",
    ph3: "",
    email1: "marigoldchry@gmail.com",
    email2: "",
    website: "www.hotelmarigold.com",
    overview: "Marigold Hotel & Resort is located on the side of Changanacherry bypass road which is 18 km from Kottayam town. At Marigold Hotel you can roam into a grove of nutmeg, coconut, vanilla or pepper vine in a homely atmosphere with lawn spread garden with flowers. Marigold is situated in the middle of Kerala, the God’s own country, making it an ideal destination to access multiple topographies – like the backwaters, beaches, hill stations of Kerala. Marigold hotel and resort has a homely atmosphere with 7 large well-furnished bed rooms with a verandah facing the meticulously maintained spice garden and green lawns in an ecofriendly environment landscaped by nature.",
    facilities: "Parking, Restaurant, Air Conditioner, Television, Doctor on Call, Color TV, Conference hall, Non , Travel desk",
    latitude:9.454946, 
    longitude:76.542184,
  ),
  Hotel(
    name: "Orchid Residency",
    image: "assets/stay/ho-orchid.jpg",
    classification: "",
    address: "Pulimoodu Junction, Kottayam \nPin: 686001",
    ph1: "+919446071141",
    ph2: "+914812563141",
    ph3: "+914812565141",
    email1: "mail@orchidresidency.com",
    email2: "",
    website: "www.orchidresidency.com",
    overview: "Welcome to Orchid Residency Kottayam. We are situated at the heart of Kottayam town with easy accessible transportation Hubs and only few miles to the world’s greatest backwaters Kumarakom. We are equipped with variety of rooms, multi cuisine restaurant, 24hr coffee shop and banquet halls. The warmly decorated rooms with wood furnishings and tile floors feature free Wi-Fi and TVs. Room service is available 24/7. Breakfast and parking are complimentary. There’s a casual international restaurant and a rooftop buffet-style eatery. Other amenities include a business centre and 3 meeting rooms.",
    facilities: "High speed Wi-fi, Parking, Restaurant, Locker, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, Baby-sitting, Banquet hall, Car hire service, Chinese dishes, Coffee shop, Color TV, Conference hall, Conference hall, Credit Card Accepted, Currency exchange, Food, Group Check-in, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, MICE (Meetings, Incentives, Conferences & Events), Non , North Indian Dishes, Online reservation, Private party area, Refrigerator, , South Indian Dishes, Tour Packages, Transport and Guide Services, Travel desk, Video-conferencing facilities & Web casting facilities, Weddings in Kerala, Wi-fi Lobby",
    latitude:9.589014,
    longitude:76.521104,
  ),
  Hotel(
    name: "Palakunnel Tourist Hotel",
    image: "assets/stay/ho-palakunnel.jpg",
    classification: "",
    address: "M.C Road, Ettumanoor\nKottayam, Pin: 686631",
    ph1: "+919895088311",
    ph2: "+914812535281",
    ph3: "+914812536231",
    email1: "palakunneltouristhotel@gmail.com",
    email2: "",
    website: "www.palakunneltouristhotel.com",
    overview: "Palakunnel tourist hotel offers accommodation in Ettumanoor. Guests can enjoy the on-site restaurant. Free private parking is available on site. Certain rooms include a seating area for your convenience. Rooms include a private bathroom. There is a 24-hour front desk at the property. Cochin is 45 km from Palakunnel residency, while Alleppey is 27 km away. Kochi International Airport is 57 km from the property.",
    facilities: "Parking, Restaurant, Locker, Air Conditioner, Television, Doctor on Call, 24-hour Room Service, Banquet hall, , Color TV, Conference hall, Hairdryer, Handicap Facilities, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, , Travel desk",
    latitude:9.669451,
    longitude:76.556073,
  ),
  Hotel(
    name: "Paradise Resorts",
    image: "assets/stay/ho-paradise.jpg",
    classification: "",
    address: "Near Nazreth Church\nKumarakom South P. O.\nKottayam, Pin: 686563",
    ph1: "+919745000498",
    ph2: "+918088140150",
    ph3: "+914812524721",
    email1: "info@paradisein.com",
    email2: "",
    website: "www.paradisein.com",
    overview: "We aim to consistently exceed expectations with high quality cottages and incomparable hospitality. Our goal is to provide a flawless, relaxing and memorable experience, time after time. Enjoy more fulfilling relationships with your loved ones in the Garden of Eden. Design your own dream vacation with endless choice. Spend your time with lots of fun and joy. Enjoy the anticipation, travel, try new places, experiences and flavours and cherish and share the amazing memories.",
    facilities: "Restaurant, Air Conditioner",
    latitude:9.586243,
    longitude:76.423362,
  ),
  Hotel(
    name: "Royal Riviera Hotels & Resorts",
    image: "assets/stay/ho-royalriviera.jpg",
    classification: "",
    address: "Cheepunkal P. O., Kumarakom,\nKottayam, Pin: 686563",
    ph1: "+919562736000",
    ph2: "+919562626000",
    ph3: "+914812526702",
    email1: "royalrivierakumarakom@gmail.com",
    email2: "info@royalriverkumarakom.com",
    website: "www.royalrivierakumarakom.com",
    overview: "Nestled on the bank of one of the tributaries of Vembanad lake in Kumarakom, The Royal Riviera spread across in more than seven acres. The palatial building is built in precise plannimg and eco- friendly to provide maximum freedom for relaxation to our guests. Each and every suite is artistically designed and furnished with all modern amenities. The view of panoramic beauty of paddy fields and flowing life through the canal from the suite can evoke the poet in you. Well trained service personnel are our asset to provide our guests to feel homely.Well trained service personnel are our asset to provide our guests to feel homely because we value our guests as Gods, as the scriptures say 'Adhithi Devo Bhava'(Guest is God). In addition to strong compound wall we have round the clock security personnel to keep guard and ensure security of our valued guests.",
    facilities: " Parking, Restaurant, Television,  Doctor on Call,24-hour Room Service, Ayurveda Center, Boating facilities, , Children's Play Area, Coffee Maker, Conference hall, Internet facility, Swimming Pool, Travel desk",
    latitude:9.638659,
    longitude:76.427415,
  ),
 Hotel(
    name: "Serenity at Kanam Estate",
    image: "assets/stay/ho-serenity.jpg",
    classification: "",
    address: "Payikad, Manimala, Kanam P. O.,\nVazhoor, Kottayam, Pin: 686515",
    ph1: "+914812456353",
    ph2: " ",
    ph3: " ",
    email1: "reservations@malabarescapes.com",
    email2: "",
    website: "http://www.serenityvillaresort.com/",
    overview: "Serenity is surrounded by tropical gardens.Thoroughly designed, yet retaining the heritage ambience, this dream come true 1920 the state bungalow blends into an unspoiled tropical setting.",
    facilities: " ",
    latitude:9.542700,
    longitude:76.696057,
  ),
  Hotel(
    name: "Sunstar Residency & Food Plaza Pala",
    image: "assets/stay/ho-sunstar.jpg",
    classification: "",
    address: "OPP. KSRTC Bus station\nMarthoma church road, Pala\nKottayam, Pin: 686575",
    ph1: "+916238355676",
    ph2: "+914822298500",
    ph3: "+914822298600",
    email1: "sunstarhospitalitypala@gmail.com",
    email2: "sunstarreservations@gmail.com",
    website: "www.sunstarresidencypala.com",
    overview: "Sunstar Residency is the best business luxury hotel in Pala in the central district of Kerala. We offer the whole range of amenities for a comfortable stay in suite, executive, deluxe, standard rooms and a family multi cuisine restaurant. Sunstar family restaurant serves a range of delightful food including Nadan, Chinese, North Indian, Continental, Biriyani, Seafood , Fried Chicken, BBQ, Pizza, Tandoor, Thattukada, and of course Shappu Varieties in addition to verities of snacks.\nProximity to tourist centres and pilgrims centres is the biggest advantage for choosing Sunstar residency as an ideal place to stay. Vagamon,Thekkady and Kumarakom tourist destinations are just 1.5 hour travel to reach. The travel to these destinations itself is a memorable one with beautiful sceneries and greeneries.\nAlphonsa tomp, Sabarimala lord ayyappan temple and Kadappattur temple are few of the temples frequented by thousands of pilgrims.",
    facilities: " High speed Wi-fi,  Parking,  Restaurant,  Bar, Television,  Doctor on Call,24-hour Room Service, Baby-sitting, Car hire service, Chinese dishes, Coffee Maker, Coffee shop, Color TV, Conference hall, Conference hall, Credit Card Accepted, Currency exchange, Flight status, Food, Group Check-in, Hairdryer, Internet facility, Iron / Ironing Board, Laundry, Lounge , North Indian Dishes, Online reservation, Photocopying, Private party area, Secretarial services, South Indian Dishes, Tour Packages, Travel desk, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp",
    latitude:9.714813,
    longitude:76.689867,
  ),
  Hotel(
    name: "Tamarind KTDC Easy Hotel",
    image: "assets/stay/ho-tamarind.jpg",
    classification: "",
    address: "Manakkachira, A.C. Road\nChanganacherry, Kottayam\nPin: 686101",
    ph1: "+919400008662",
    ph2: "+914812400899",
    ph3: " ",
    email1: "tamarindchanganacherry@ktdc.com",
    email2: " ",
    website: " www.ktdc.com/tamarind/changanacherry",
    overview: "Changanacherry is known as the gateway to the high ranges and the backwaters of Kuttanad. In the past, the region was known as Anchu Vilakkinta Pattanam, which in local language means ‘Town of five fire lamps.’ It once formed the northern boundary of the erstwhile princely state of Travancore.\nThe property is located on the Alleppey-Changanacherry road, which provides an opening to the life in the Kuttanad region.",
    facilities: " Restaurant, Boating facilities ",
    latitude:9.433836,
    longitude:76.532331,
  ),
  Hotel(
    name: "The Manor Backwater Resort",
    image: "assets/stay/ho-themanor.jpg",
    classification: "",
    address: "Cheepunkal, Kumarakom\nKottayam, Pin: 686563",
    ph1: "+914812526328",
    ph2: "+914812526329",
    ph3: "+914814526330",
    email1: "reservations@manorbackwaterresort.com",
    email2: "admin@manorbackwaterresort.com",
    website: "www.manorbackwaterresort.com",
    overview: "Manor Backwater Resort is a top class luxury resort built in contemporary Indian style inspired by traditional Kerala architecture. The resort is constructed with an eye for detail in comfort & elegance. All the rooms, outlets, gym, conference and board rooms are air conditioned for your comfort. Manor exudes old fashioned charisma & elegance. Here design is everything and hospitality reigns supreme. Explore the rooms and facilities of the Manor.",
    facilities: " Parking,  Restaurant,  Air Conditioner,  Television,  Doctor on Call,24-hour Room Service, Banquet hall, , Color TV, Conference hall, Fitness Center, Indoor games, Swimming Pool, Tour Packages, Travel desk ",
    latitude:9.637587,
    longitude:76.432122,
  ),
  Hotel(
    name: "The Palms",
    image: "assets/stay/ho-thepalms.jpg",
    classification: "",
    address: "Near Federal Bank, SH 1,\nChingavanam, Kottayam, Pin: 686531",
    ph1: " +914812432154",
    ph2: " ",
    ph3: " ",
    email1: "palms2012@yahoo.com",
    email2: "",
    website: " http://www.thepalmshotel.in/",
    overview: "When you are at The Palms, for a business trip or for a leisure holiday, our excellent and affordable services make us the best choice for your purpose. We are located at the heart of Kottayam, less than fifteen minutes drive from the beautiful town. At The Palms we define hospitality as luxurious, comfy and adaptable to the requirements of each guest. The Palms interiors are designed with stylish architectures and you are served with Indian or western nouvelle cuisine food and world class amenities. We have designed a casual atmosphere to suit your needs; you can spend your moments as you wish. We are really proud and privileged to welcome you to the royal inn, because The Palms hosts you with unprecedented services.",
    facilities: " ",
    latitude:9.519353,
    longitude:76.524943,
  ),
  Hotel(
    name: "The Windsor Castle Leisure Hotel",
    image: "assets/stay/ho-windsorcastle.jpg",
    classification: "",
    address: "Kodimatha, Kottayam\nPin: 686039",
    ph1: "+919544086111",
    ph2: "+914812363637",
    ph3: "+914812363638",
    email1: "info@thewindsorcastle.co.in",
    email2: "edp@thewindsorcastle.co.in",
    website: "http://www.thewindsorcastle.co.in/",
    overview: "Hotel Windsor Castle, a downtown deluxe hotel, located in Kottayam, Kerala. It is the gateway to Kumarakom. The most sought after tourist destination in Kottayam. Situated in the most picturesque surrounding of the Vembanad Lake, this leisure hotel stands above the rest in style, class, and luxury. Set on a sprawling 20 acres of lush foliage and landscaped lawns this leisure hotel provides the ideal getaway for a relaxed and enriching experience. The Windsor Castle is just 60km from Cochin Airport and only 2km from Kottayam Railway Station. A centrally air-conditioned hotel with state-of-the-art rooms. WiFi on request, swimming pool, doctor on call, 24 hours room service, multi-cuisine restaurant, club bar, book shop, beauty parlour, sprawling lawns, boating in the backwaters and above all parking space for more than 100 cars.",
    facilities: " High speed Wi-fi,  Parking,  Restaurant,  Bar, Locker,  Air Conditioner,  Television,  Doctor on Call,24-hour Room Service, Ayurveda Center, Banquet hall, Beauty saloon, Boating facilities, Car hire service, Chinese dishes, Coffee shop, Conference hall, Conference hall, Credit Card Accepted, Exhibition hall, Fitness Center, Food, Gift Shop, Group Check-in, Hairdryer, Handicap Facilities, Homely Kerala Food, Indoor games, Laundry, Library, Lounge , Medical Tourism, Meet-and-Greet Services, Mini , North Indian Dishes, Online reservation, Photocopying, Private party area, Refrigerator, , South Indian Dishes, Spa, Swimming Pool, Tour Packages, Travel desk, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp, Workstations, Yoga Centre ",
    latitude:9.572667,
    longitude:76.518750,
  ),
  Hotel(
    name: "Varsha International",
    image: "assets/stay/ho-varsha.jpg",
    classification: "",
    address: "Kuruppanthara, Kottayam",
    ph1: "+919645525559",
    ph2: "+914829244324",
    ph3: "+914829244603",
    email1: "hotelvarshaktym@gmail.com",
    email2: "",
    website: "www.varshainternationalresidency.com",
    overview: "Far from all hurry and bustle, right in the lap of nature, is a place for those who want to stay in peace and quiet with all that makes life most pleasant and most joyful. Varsha International offers you a life in the lap of nature in an eco-friendly environment. Kuruppanthara is neither too near nor far from Kottayam town that has Kumarakom as its prestigious tourist centre with its coconut lagoon, bird sanctuary, paddy fields and boating facilities. Away from the heart of the town, you enjoy all the rural beauty, and you reach it in no time when you wish. So, here we are, welcoming you, whether you are on a business tour or a holiday trip with your family.",
    facilities: " Parking,  Restaurant,Air Conditioner,  Television,  Doctor on Call,24-hour Room Service, Banquet hall, , Children's Play Area, Coffee Maker, Color TV, Conference hall, Laundry, Travel desk ",
    latitude:9.743331,
    longitude:76.514076,
  ),
  
];