class Grihasthali {
  final String name,
      image,
      classification,
      address,
      ph1,
      ph2,
      ph3,
      email1,
      email2,
      website,
      overview,
      facilities;
      double latitude,  longitude;
      
    

  Grihasthali({
    required this.name,
    required this.image,
    this.classification="",
    required this.address,
    required this.ph1,
    this.ph2 = "",
    this.ph3 = "",
    required this.email1,
    this.email2 = "",
    this.website = "",
    required this.overview,
    required this.facilities,
    required this.latitude ,
    required this.longitude ,
  });
}

List<Grihasthali> grihasthali = [
  Grihasthali(
    name: "Kodianthara Heritage Home",
    image: "assets/stay/gr-kodianthara.jpg",
    classification: "Heritage Classic",
    address: "Behind St. John Knanaya Church\nKumarakom, Kottayam, Pin: 686563",
    ph1: "+919495333849",
    ph2: "+919497663128",
    ph3: "+914812524314",
    email1: "crispinku@gmail.com",
    email2: "",
    website: "http://www.kodianthara.in/",
    overview: "Kodianthara Tharavadu was built in 1850 by Uthup Ittiavira and renovated in 2002 by Crispin Uthup, 5th generation of the family. The 1st structure of the house with centre courtyard surrounded by 6 rooms with modern amenities gives you an idea of Kerala architecture and culture. A Hotel Management Graduate, Crispin was in Merchant Navy as a Catering Officer from 1981 to 2005. Since then the Crispins are doing hospitality service with great passion to carry forward the inheritance. Surrounded by backwaters the 2.50 acre rubber, fruits and veg farm is an ideal retreat for lovers of peace and tranquility. It is also the ideal place to relish the traditional Syrian Christian cuisine. Its location is at the heart of Kumarakom Market place.",
    facilities: "A/c Room, Ayurveda Center, Bar, Boating facilities, Cable / Satellite TV, Car hire service, Car parking and valet services, Children's Play Area, Chinese dishes, Coffee shop, Color TV, Cultural Programs, Currency exchange, Doctor-on-call, Fitness Center, Food, Hairdryer, Handicap Facilities, High speed Wi-fi access, Homely Kerala Food, Indoor games, Internet facility, Iron / Ironing Board, Laundry, Library, Lounge Bar, Meet-and-Greet Services, Non A/c Room, North Indian Dishes, Online reservation, Private party area, Refrigerator, Restaurant, Safe Deposit Lockers, South Indian Dishes, Tour Packages, Transport and Guide Services, Travel desk, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp",
    latitude: 9.596698,
    longitude: 76.436246,
  ),
  Grihasthali(
    name: "The Mana heritage stay ",
    image: "assets/stay/gr-themana.jpg",
    classification: "Heritage",
    address: "Chengazhimattam, S H Mount P O\nNATTASSERY, Kottayam, Pin: 686006",
    ph1: "+918547511793",
    ph2: "+914812311793",
    ph3: "+919446912132",
    email1: "themanaheritagestay@gmail.com",
    email2: "chengazhimattam@gmail.com",
    website: "",
    overview: "Chengazhimattom mana is an ancient typical Kerala brahmin house situated in the banks of Meenachil river. The building is more than 300 years old. The traditional layout of a mana consist of an open courtyard in the middle and it is called “nadumittam”. The mana is a typical “naalukettu” form of Kerala brahmin houses. “The mana” is situated in the middle of a hectre of land. This consist of many plants and trees including mainly nutmeg, banana, coconut etc.\n\nThe building is surrounded with greenery. Also there are “Kaavu” which is a worshipping place for snakes and a very good example of an ecosystem because the area around the “kaavu” is undisturbed.",
    facilities: "24-hour Room Service, Car parking and valet services, Food, Hairdryer, High speed Wi-fi access, Homely Kerala Food, Internet facility, Iron / Ironing Board, Non A/c Room, Safe Deposit Lockers, South Indian Dishes",
    latitude: 9.605565,
    longitude: 76.536699,
  ),
  
  Grihasthali(
    name: "Rishi Heritage Village",
    image: "assets/stay/gr-rishi.jpg",
    classification: "Heritage",
    address: "Poonjar, Kottayam",
    ph1: "+919037776000",
    ph2: "+914822272263",
    ph3: "",
    email1: "kuriansn@yahoo.com",
    email2: "info@rishihospital.com",
    website: "https://rishihospital.com/rishi-heritage-village/",
    overview: "Tucked away conveniently in the quaint little village of Edamala – Poonjar with beautiful green landscapes and picturesque valleys, Rishi Heritage Village offers a breathtaking view from literally every single direction. With legendary service, authentic Ayurvedic treatments and spacious suits, Rishi Heritage Village offers a splendid experience for the holistic break from your busy schedules. With its aura of historic charm and scenic wonder, Rishi Heritage Village is providing an unmatched experience for the customers. At the cottages state of the art infrastructure with most modern facilities are incorporated in an elegant way. The heritage village spreads over 39000 square meters of land and has more than 50 species of trees and its home for more than 30 species of birds in the season.",
    facilities: "A/c Room, Ayurveda Center, Doctor-on-call, Food, Group Check-in, Homely Kerala Food, Medical Tourism, Meet-and-Greet Services, Non A/c Room, South Indian Dishes, Tour Packages, Work Desk with Lamp, Yoga Centre",
    latitude: 9.661592346404573,
    longitude: 76.84810999617339,
  ),
  Grihasthali(
    name: "Cherukattu Mana Heritage",
    image: "assets/stay/gr-cherukattu.jpg",
    classification: "Heritage",
    address: "Near Devi temple\nThrikkarthika road, Kumaranalloor,\nKottayam, Pin: 686016",
    ph1: "+917902439339",
    ph2: "",
    ph3: "",
    email1: "rahul13586@gmail.com",
    email2: "rahul13586@gmailcom",
    website: "",
    overview: "The 380-year-old Brahmin homestead of Cherukattu Mana is situated on the banks of Meenachil river at Kumaranalloore, one of in Kerala. About 10 generations of Cherukattu family had been living in this house, constructed with laterite and wood in the traditional architectural style of Nalukettu. The building consists of a rectangular structure having four walls, joined together with a central open courtyard. The Cherukattu Mana has a frontal open porch, central courtyard, northern block, granary, attic, cellar, 3 bedrooms, 2 storerooms, 2 attached bathrooms, kitchen and rear verandah. The building is designed in such a way that sunlight falls on every structure in the morning. The skill of expert carpenters is reflected on the timber walls and roof interjunctions. The family of Cherukattu Mana belongs to the lineage of Rig Veda Brahmins of Bhargava gotra who had migrated from Panniyoor, a Brahmin village in Malabar to Kumaranalloor about 380 years ago. The descendents have been engaged",
    facilities: "24-hour Room Service, Boardroom, Boating facilities, Car parking and valet services, Cultural Programs, Doctor-on-call, Flight status, Florist, Food, Group Check-in, High speed Wi-fi access, Homely Kerala Food, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, Medical Tourism, Online reservation, Private party area, Refrigerator, Safe Deposit Lockers, Translation / interpretation services (on request), Transport and Guide Services, Travel desk, Weddings in Kerala, Wi-fi Lobby, Yoga Centre",
    latitude: 9.625357726500315,
    longitude: 76.52978778082827,
  ),
  Grihasthali(
    name: "Kuruvinakunnel Tharavad",
    image: "assets/stay/gr-kuruvinakunnel.jpeg",
    classification: "Heritage",
    address: "Kuruvinakunnel, Edamattom\nEdamattom, Kottayam, Pin: 686578",
    ph1: "+919447488579",
    ph2: "+914822236234",
    ph3: "",
    email1: "info@kuruvinakunnelheritage.com",
    email2: "www.kuruvinakunnelheritage.com",
    website: "http://www.kuruvinakunnelheritage.com",
    overview: "The Kuruvinakunnel Tharavadu (ancestral home) was built around 400 years back by our forefathers, The Kuruvinakunnel family originated from this ancestral home, the roots are deep, the tree is strong and branches are spread far and wide across the globe in domains like IT, Hotel Industry, Plantations etc. We have the pleasure in welcoming you into our Tharavadu which will enable you to relive couple of your days in the distant past in a 400 year old Christian Tharavadu. The bungalow is located in the midst of a rubber estate far away from the hustle & bustle of the city. We offer the bungalow with two fully furnished air conditioned bath attached rooms for our guests. Enjoy the tranquil atmosphere revitalising your mind and body, you are welcomed, looked after and cared for by the family. Your privacy is assured as the bungalow is away from the family residence.",
    facilities: "A/c Room, Coffee Maker, High speed Wi-fi access, Homely Kerala Food, Internet facility, Iron / Ironing Board, Library, Online reservation, Private party area, Refrigerator, Wi-fi Lobby, Work Desk with Lamp",
    latitude: 9.688911943535796,
    longitude: 76.72176424349364,
  ),
  
  Grihasthali(
    name: "Kalaketty Estate",
    image: "assets/stay/gr-kalaketty.jpg",
    classification: "",
    address: "Pottamkulam, Kanjirappally\nKalaketty, Kottayam",
    ph1: "+919447180240",
    ph2: "+914828235223",
    ph3: "+914828236999",
    email1: "vpkurian@kalakettyestate.com",
    email2: "info@kalakettyestate.com",
    website: "http://kalakettyestate.com/",
    overview: "Nestled in the midst of a lush green 150 acre estate is our traditional Syrian Christian home. We are a family of planters who have been living in this ancestral home for the past 3 generations. This house was built in 1930 by my grandfather, Mr. K. V. Joseph Pottamkulam. The house is set amidst old and huge mahogany, teak, mangostene, nutmeg and clove trees and overlooks lush green paddy fields. Rubber is the main crop we grow on the estate, besides cocoa, tapioca, pepper, vanilla, rice, coconuts, bananas and pineapples. Your stay with us at our estate home would be a good opportunity to experience life as we do in the plantation. You will be well cared for and comfortable in our home, and your privacy is assured since the outhouse is independent from the family residence.",
    facilities: "",
    latitude: 9.613921,
    longitude: 76.78566599999999,
  ),
];