class Resort {
  final String name,
      image,
      classification,
      address,
      ph1,
      ph2,
      ph3,
      email1,
      email2,
      website,
      overview,
      facilities;
      double latitude,longitude;

  Resort({
    required this.name,
    required this.image,
    this.classification ="",
    required this.address,
    required this.ph1,
    this.ph2 = "",
    this.ph3 = "",
    required this.email1,
    this.email2 = "",
    this.website = "",
    this.overview="",
    this.facilities ="",
    required this.latitude ,
    required this.longitude ,
  });
}

List<Resort> resort = [
  Resort(
    name: "Contour Backwaters Resort &\nConvention Centre",
    image: "assets/stay/re-contour.jpg",
    classification: "5 Star",
    address: "1st Bridge, AC. Road, Manakkachira,\nChanganassery, Kottayam, Pin: 686101",
    ph1: "+918606531144",
    ph2: "+914812404100",
    ph3: "",
    email1: "sales@contourresorts.com",
    email2: "",
    website: "https://contourbackwaters.com/",
    overview: "Welcome to Contour Resorts, a unique collection of eco-friendly and eco sensitive concepts, from the finest selection of cuisine to the warm and attentive services. The essence of the 'Contour' experience is in providing each one of our guest with an experience that is unique or special to all, service that goes far beyond expectations.",
    facilities: " High speed Wi-fi,  Parking,  Restaurant,  Bar, Locker,  Air Conditioner,  Television,  Doctor on Call\n24-hour Room Service, Banquet hall, Boardroom, Car hire service, Chinese dishes, Coffee Maker, Color TV, Conference hall, Conference hall, Fitness Center, Food, Group Check-in, Hairdryer, Homely Kerala Food, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, Mini , North Indian Dishes, Refrigerator, , South Indian Dishes, Swimming Pool, Travel desk, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp",
    latitude:9.433389,
    longitude:76.528694 ,
  ),
  Resort(
    name: "Ashirwad Heritage Resorts",
    image: "assets/stay/re-ashirwad.jpg",
    classification: "4 Star",
    address: "Ward No.2, Chakrampady\nKumarakom, Kottayam, Pin: 682011",
    ph1: "+918943334605",
    ph2: "+914812527100",
    ph3: "",
    email1: "info@ashirwadheritageresorts.com",
    email2: "",
    website: "",
    overview: "Ashirwad is a four star classified bar attached hotel with 24x7 check in, multilingual staff, multi cuisine restaurant with a group of experienced chef and team from UAE, swimming pool, banquet hall, board room, high speed wifi rooms, lobby and ample car parking. Our room rates are very flexible and we give value to each and every single rupees spend by our guest. We ensure that once the guest checks in, from the very first foot step of them until their check out they will have friendly and homely atmosphere and also the traditional taste of Kerala backwaters and their own homely food. Ashirwad works in the motto, Live in style & stay luxuriously in very economical rate.",
    facilities: " Parking,  Restaurant, Locker, Doctor on Call\nCoffee Maker, Coffee shop, Conference hall, Hairdryer, Internet facility, Iron / Ironing Board, Laundry, Travel desk",
    latitude:9.614424,
    longitude:76.433305,
  ),
  Resort(
    name: "Winter Vale Green Stay",
    image: "assets/stay/re-wintervale.jpg",
    classification: "",
    address: "Kurisumala Ashram Junction\nVazhikkadavu, Vagamon\nKottayam, Pin: 685503",
    ph1: "+918111807771",
    ph2: "+919048322916",
    ph3: "",
    email1: "info@wintervalestay.com",
    email2: "",
    website: "http://www.wintervalestay.com/",
    overview: "Winter Vale is an eco-friendly green stay that offers complete serenity to those looking for an escape into nature. Sprawling across 20 acres of lush greenery, Winter Vale is set in a soul-stirring ambience. Come and experience a walk with us into the green and peaceful valley of Vagamon. We assure you a unique and memorable holidaying experience. Each of our cottages is duly furnished in harmony with the nature and offers breathtaking valley view and clean air of hills. A stay with us will take you away from the hustle and bustle of busy life and deliver you complete comfort, peace and tranquility. To cater the different needs of our guests, whether they are a big family group or a lonely traveler we have suitable space for all.",
    facilities: "Restaurant, Television, Car hire service, Children's Play Area, Coffee Maker, Color TV, Conference hall, Food, North Indian Dishes, Online reservation, Photocopying, Scanning services, South Indian Dishes, Swimming Pool, Transport and Guide Services, Work Desk with Lamp",
    latitude:9.686200 ,
    longitude:76.905200 ,
  ),
  Resort(
    name: "Lake village Heritage Resort",
    image: "assets/stay/re-lake.jpg",
    classification: "",
    address: "The Windsor Castle, Kodimatha,\nKottayam, Pin: 686039",
    ph1: "+919544086111",
    ph2: "+919447784052",
    ph3: "+914812363637",
    email1: "edpwindsorcastle@gmail.com",
    email2: "",
    website: "https://thewindsorcastle.co.in/",
    overview: "Typical Kerala architecture has been recreated from old Tharavadu and llams or ancestral homes providing the ideal ambience for a relaxed stay. Set amongst the verdant coconut palms swaying to the gentle breeze with lazy backwaters flowing by, the village is an idyllic destination for your holiday. The cottages are an artful blend of the old and new with modern amenities to make your stay comfortable. Each cottage imparts a unique feeling of staying afloat a houseboat with the backwater gently lapping the sides.",
    facilities: "",
    latitude:9.571223 ,
    longitude:76.518271 ,
  ),
    Resort(
    name: "Kalathil Lake Resort",
    image: "assets/stay/re-kalathil.jpg",
    classification: "",
    address: "Near Indo American Hospital\nChemmanakary, Akkarappadam (Post)\nVaikom, Kottayam, Pin: 686143",
    ph1: "+919946711182",
    ph2: "+919946711184",
    ph3: "+919946711183",
    email1: "reservations@kalathillakeresort.com",
    email2: "gm@kalathillakeresort.com",
    website: "https://kalathillakeresort.com/",
    overview: "Facing the lake on eastern, western, and northern sides and lagoon on the southern side, the resort gives a spectacular view to the visitors. The villas are erected on pillars in water. Interspersed with meandering canals and paved walkways, the resort is a soothing experience with its sheltered aquatic spa, fresh water pond, manicured lawns, and swaying coconut palms. Free high speed Wi-Fi, internet in all the rooms, in-room dining and free private parking are available.",
    facilities: "Parking,  Air Conditioner,  Restaurant, Television, Doctor on Call\n24-hour Room Service, Ayurveda Center, , Coffee shop, Color TV, Internet facility, Travel desk, Wi-fi Lobby",
    latitude:9.792733 ,
    longitude:76.376331 ,
  ),
  Resort(
    name: "Waterscapes (KTDC)",
    image: "assets/stay/re-waterscapes.jpg",
    classification: "",
    address: "KTDC Backwater Resort\nKumarakom North\nKottayam, Pin: 686563",
    ph1: "+919400008621",
    ph2: "+919400008622",
    ph3: "+914812525861",
    email1: "waterscapes@ktdc.com",
    email2: "",
    website: "www.ktdc.com/water-scapes",
    overview: "Waterscapes - this exotic backwater resort, on the shores of Vembanad lake is located inside the Kumarakom Bird Sanctuary, which draws migratory birds from as far away as Siberia. It is the only resort in the destination located inside the bird sanctuary and is noted for its independent huts that stand on stilts and is a place teeming with mangrove vegetation.",
    facilities: "Restaurant, Bar, 24-hour Room Service, Ayurveda Center, Boating facilities, Car hire service, Conference hall, Currency exchange, Laundry, Swimming Pool, Tour Packages",
    latitude:9.583333 ,
    longitude:76.433333 ,
  ),
  Resort(
    name: "Tharavadu Heritage Home",
    image: "assets/stay/re-tharavadu.jpg",
    classification: "",
    address: "Govt. Boat Jetty, Kumarakom,\nKottayam, Pin: 686563",
    ph1: "+919447152447",
    ph2: "+919446503632",
    ph3: "+914812525230",
    email1: "tharavaduhome@gmail.com",
    email2: "tharavadu@asianetindia.com",
    website: "http://www.tharavaduheritage.com/",
    overview: "Enjoy the ambiance of a traditional Kerala house in the banks of the cool and calm Kumarakom. Tharavadu means family house in local language. Heritage Home is a 140 years old traditional Kerala Syrian Christian family house, located near the river bank. The recently renovated house is having all modern facilities. It is surrounded with small rivers and natural beauty. The promoters are keen to offer nature oriented services and a big NO to plastics in this environment friendly villa.",
    facilities: "High speed Wi-fi,  Parking,  Restaurant, Air Conditioner,  Television,  Doctor on Call\n 24-hour Room Service, Boating facilities, , Children's Play Area, Color TV, Food, Homely Kerala Food, Internet facility, Laundry, Non , North Indian Dishes, Online reservation, South Indian Dishes, Swimming Pool, Wi-fi Lobby",
    latitude:9.595797 ,
    longitude:76.431090 ,
  ),
  Resort(
    name: "Kumarakom Pearlspot Resort",
    image: "assets/stay/re-pearlspot.jpg",
    classification: "",
    address: "Cheepunkal P.O, Kavanatinkara\nKumarakom, Kottayam, Pin: 686563",
    ph1: "+919061234528",
    ph2: "+919061234529",
    ph3: "",
    email1: "pearlspotresort@gmail.com",
    email2: "nabielm@gmail.com",
    website: "",
    overview: "Pearl Spot Resort & Spa provides 10 elegantly furnished A/C rooms; 7 deluxe and 3 suites well equipped with all the modern facilities, luxury and comfort for the guests.",
    facilities: "Parking, Air Conditioner, Television, Doctor on Call",
    latitude: 9.630175,
    longitude: 76.430227,
  ),
 Resort(
    name: "Rhythm Kumarakom",
    image: "assets/stay/re-rhythm.jpg",
    classification: "",
    address: "Amankari Road, Kumarakom\nKottayam, Pin: 686563",
    ph1: "+919072845000",
    ph2: "+919072845001",
    ph3: "+914812525500",
    email1: "gm.kum@rhythmhospitality.com",
    email2: "",
    website: "https://www.rhythmhospitality.com/",
    overview: "AVEDA KUMARAKOM - The serene village of Kumarakom has a remarkable boutique luxury resort in the picturesque and naturally endowed lake Vembanad, by name Aveda Kumarakom. Aveda resort and spa is a tranquil spa resort on the verdant shores of Vembanad Lake. The luxurious resort offers a heavenly blissful stay in the tranquil backwaters and offers marvelous sceneries from its beautiful and comfortable cottages and arenas. The resort has one of the largest swimming pools in the country with cottages lined on either side of the pool. The cool serene pool water extending 150 metres seems endless and so inviting. The resort is set in traditional Kerala stylewith modern amenities and is 5 km from the Kumarakom Bird Sanctuary and 83 km away from Cochin International Airport. The resort is designed to relax and rejuvenate soul, body and mind and appreciate the natural beauty of the backwaters and its quiet surroundings with unique bird sightings.",
    facilities: "High speed Wi-fi, Parking, Restaurant, Locker, Air Conditioner, Television, Doctor on Call",
    latitude:9.589767, 
    longitude:76.425055,
  ),
  Resort(
    name: "Cocobay Resort",
    image: "assets/stay/re-cocobay.jpg",
    classification: "",
    address: "Kumarakom North\nKottayam, Pin: 686563",
    ph1: "+914232443904",
    ph2: "+914232443580",
    ph3: "+914232440978",
    email1: "reservations@cocobayresort.net",
    email2: "",
    website: "https://www.cocobayresort.net/",
    overview: "Cocobay Resort is located in Kumarakom, a backwater hamlet - the most sought after holiday destination in Kerala. Nestled amid swaying palms, the resort fronts the magnificence of the Vembanad Lake with its canals, streams and intricate network of waterways. The resort is accessible only by water and is embraced by the lake. The resort offers 22 air-conditioned suites, designed in typical Kerala architecture. Its ethnic ambience blends with modern facilities like mini-fridge, coffee/tea maker, designer bathrooms etc. Verandahs have a splendid view of the lake where you can watch stunning sunsets. The resort is located 70 Kms from Cochin International Airport, 16 Kms from Kottayam Railway Station and 90 minutes by road from Cochin International Airport.",
    facilities: " Parking, Restaurant, Locker, Television, Doctor on Call",
    latitude:9.618435,
    longitude:76.427190,
  ), 
  Resort(
    name: "Edassery Kayal Resort",
    image: "assets/stay/re-edassery.jpg",
    classification: "",
    address: "Ward # 09, Block#12\nNear Nasrath Church, Kumarakom South\nKottayam Pin: 686563",
    ph1: "+919495006626",
    ph2: "+914812453762",
    ph3: "",
    email1: "co@eghplanet.com",
    email2: "",
    website: "https://www.edasseryonline.com/",
    overview: "",
    facilities: "Television, Doctor on Call",
    latitude: 9.589033,
    longitude: 76.423740,
  ), 
  Resort(
    name: "The Zuri Kumarakom\nKerala Resort & Spa",
    image: "assets/stay/re-thezuri.jpg",
    classification: "",
    address: "V 235 A1 to A54, Karottukayal\nKumarakom, Kottayam, Pin: 686563",
    ph1: " +914812527272",
    ph2: "+914812527282",
    ph3: "",
    email1: "reservations.kumarakom@thezurihotels.com",
    email2: "",
    website: "https://www.thezurihotels.com/",
    overview: "",
    facilities: "",
    latitude: 9.593542,
    longitude: 76.424971,
  ), 
  Resort(
    name: "Saro Lake County",
    image: "assets/stay/re-saro.jpg",
    classification: "",
    address: "1/392, Bankpady\nKumarakom, Kottayam, Pin: 686566",
    ph1: "+917736002377",
    ph2: "+914812523777",
    ph3: "",
    email1: "info@sarolakecounty.com",
    email2: "",
    website: "http://sarolakecounty.com",
    overview: "Welcome to Saro Lake County, a boutique resort unlike anything you have ever seen before, featuring village atmosphere with a fresh approach. This is an ideal back water resort which is located on the banks of Vembanad, Kumarakom. Saro Lake County, boutique resort in Kumarakom offers alluring view of back waters with an ideal place for a romantic getaway for honeymoon couples. Here certain things are guaranteed such as comfortable accommodation, fine service and dining, gorgeous views of Vembanad Lake and other outstanding games. The cuisine of Saro is mainly delicious with sea food varieties such as karimeen pollichathu, fish molly, oyster and tasty homemade south Indian food by chef Kunjoong who has years of experience in the field. The resorts traditional architectural style, the fresh breeze, the trees and the sunsets view will completely make you happy. Guests can have benefits on a day cruise on house boat & visit to Kumarakom Bird Sanctuary, memorable candle light dinner.",
    facilities: "",
    latitude: 9.619621,
    longitude: 76.426525,
  ), 
];