class ServicedVilla {
  final String name,
      image,
      address,
      ph1,
      ph2,
      ph3,
      email1,
      email2,
      website,
      overview,
      facilities;
  final double latitude, longitude;

  ServicedVilla({
    required this.name,
    required this.image,
    required this.address,
    required this.ph1,
    this.ph2 = "",
    this.ph3 = "",
    required this.email1,
    this.email2 = "",
    this.website = "",
    required this.overview,
    this.facilities ="",
    required this.latitude ,
    required this.longitude ,
  });
}

List<ServicedVilla> servicedvilla = [
  ServicedVilla(
    name: "Oasis Aqua Villa",
    image: "assets/stay/sv-oasis.jpg",
    address: "Malarickal\nKanjiram, Kottayam\nPin: 686020",
    ph1: "+919447366841",
    ph2: "+919746021383",
    ph3: "",
    email1: "oasisaquavilla@gmail.com",
    email2: "shajimonvk@gmail.com",
    website: "https://oasis-aqua-villa.business.site/?utm_source=gmb&utm_medium=referral",
    overview: "OASIS AQUA VILLA provides a shared lounge and garden. Among the facilities at this property are a shared kitchen and room service, along with free WiFi throughout the property. Free private parking is available and the guest house also offers bike hire for guests who want to explore the surrounding area.\nAt the guest house, all rooms come with a wardrobe.The area is popular for cycling and fishing, and car hire is available at the accommodation.\nAlleppey is 44 km from OASIS AQUA VILLA, while Kumarakom is 10 km away. The nearest airport is Kochi International, 87 km from the guest house, and the property offers a paid airport shuttle service.",
    facilities: "A/c Room, Boating facilities, Cable / Satellite TV, Car hire service, Car parking and valet services, Color TV, Doctor-on-call, Food, High speed Wi-fi access, Homely Kerala Food, Internet facility, Non A/c Room, Online reservation, Refrigerator, South Indian Dishes, Wi-fi Lobby, Work Desk with Lamp",
    latitude: 9.568033,
    longitude: 76.485699,
  ),
 ServicedVilla(
    name: "Lake Vechoor Villas",
    image: "assets/stay/sv-lakevechoor.jpg",
    address: "Near Thanneermukkom Bund\nVaikom, Ambika Mkt P.O.\nVechoor, Kottayam\nPin: 686144",
    ph1: "+919818457417",
    ph2: "+919810132143",
    ph3: "+917510791139",
    email1: "lakevechoorvillas@gmail.com",
    email2: "",
    website: "",
    overview: "Lake Vechoor Villas is 4 acres of land situated in the bank of Vembanad Lake. It has well furnished 11 rooms with attached bathrooms, kitchen, dining, living and conference hall, and large size ponds for fishing. This property has mangroves of rare qualities, and coconut trees, and is landscaped without disturbing living faunas.",
    facilities: "",
    latitude: 9.680344,
    longitude: 76.412462,
  ),
   ServicedVilla(
    name: "Swasthi",
    image: "assets/stay/sv-swasthi.jpg",
    address: "Thonduveli, ThampalakkaduP.O\nKanjirappally, Kottayam\nPin: 686506",
    ph1: "+919074809884",
    ph2: "+914828204592",
    ph3: "",
    email1: "hello@swasthi.in",
    email2: "",
    website: "https://swasthi.in",
    overview: "The villa is a traditional Kerala Arayum Nirayum that can accommodate 2 families of 4.There are 2 air conditioned bedrooms with king size beds. Extra beds can be provided upon request. There is a kitchen, a long verandah and big bathrooms with a rain bathing option .A caretaker will be available on the premises 24x7.",
    facilities: "",
    latitude: 9.573694,
    longitude: 76.768806,
  ),  
];