class HomeStay {
  final String name,
      image,
      classification,
      address,
      ph1,
      ph2,
      ph3,
      email1,
      email2,
      website,
      overview,
      facilities;
       double  latitude,longitude;

  HomeStay({
    required this.name,
    required this.image,
    this.classification ="",
    required this.address,
    required this.ph1,
    this.ph2 = "",
    this.ph3 = "",
    required this.email1,
    this.email2 = "",
    this.website = "",
    required this.overview,
    required this.facilities,
    required this.latitude ,
    required this.longitude ,
  });
}

List<HomeStay> Homestay = [
  HomeStay(
    name: "Akkara",
    image: "assets/stay/hs-akkara.jpg",
    classification: "Diamond House",
    address: "Akkara House, Mariathuruthu P. O.\nMariathuruthu, Kottayam, Pin: 686017",
    ph1: "+919008402402",
    ph2: "+914812516951",
    ph3: "+919743218505",
    email1: "akkarahomestay@gmail.com",
    email2: "",
    website: "http://akkara.in/homestay/",
    overview: "Located on the banks of the Meenachill river in Kottayam-Kerala, just two hours down the road from Kochi lies Akkara – Home Across the River. This 215-year-old mansion has rooms with terracotta floors and a large open courtyard that leads to the river. Guests can go fishing, stay on a houseboat, cycle through pristine locales of Kottayam and relish some Syrian Christian cuisine or simply just take a trip down the river in one of our own dugout canoes. This home has four extravagant AC rooms with period architecture and furniture and attached bath. Each room at this mansion has a terrace with beautiful views of the pristine river. Sample the best of Syrian Christian cuisine at this property specially made by the host family and also savor the various social and cultural experiences that is part of the family traditions.\nYou can spend an evening with your hosts over a drink or explore our Ayurveda center or simply relax with a personal Yoga session on this magical property.",
    facilities: "A/c Room, Ayurveda Center, Boating facilities, Cable / Satellite TV, Car hire service, Car parking and valet services, Color TV, Credit Card Accepted, Food, Homely Kerala Food, Internet facility, Laundry, Library, Non A/c Room, Online reservation, Photocopying, Private party area, South Indian Dishes, Tour Packages, Weddings in Kerala, Wi-fi Lobby, Yoga Centre",
    latitude: 9.599682,
    longitude: 76.511192,
  ),
  HomeStay(
    name: "Earathu Heritage",
    image: "assets/stay/hs-earathu.jpg",
    classification: "Diamond House",
    address: "Earathu House,Elikulam P.O, Elikulam, \nKottayam, Pin: 686577",
    ph1: "+919995352464",
    ph2: "+918547025464",
    ph3: " +914822225464",
    email1: "earathuheitage@gmail.com",
    email2: "jimmyearathu@gmail.com",
    website: "www.earathuheritage.com",
    overview: "The Earathu Heritage homestay is situated in a calm and quiet village called Elikulam, 13km away from Pala. The nearest Railway Station (Kottayam) is 33km away and the nearest Airport (Cochin International Airport) is 82km away. The home is surrounded with varieties of fruit yielding trees. You can feel the beauty of nature in every corner. You will have easy access to Bharananganam Alphonsa pilgrim centre. Also it’s a good place for a halt and refreshment on your way to tourist places like Vagamon, Ramakkalmedu, Illikkal kallu, Thekkady etc. We can arrange transportation facilities to these tourist destinations on prior request. We provide you with traditional Kerala food or you can use the kitchen inside the home. You will be connected to the internet always with the free Wi-Fi provided. The moment you step in, you are our privileged guest and we treat you like you feel it as a home away from home.",
    facilities: "",
    latitude: 9.641712,
    longitude: 76.743107,
  ),
  HomeStay(
    name: "Riverdale Villa",
    image: "assets/stay/hs-riverdale.jpg",
    classification: "Gold House",
    address: "Arpookara West P.O., Karippoothattu\nKumarakom, Kottayam, Pin: 686008",
    ph1: "+919847150624",
    ph2: "+919539211315",
    ph3: "+918606332011",
    email1: "riverdalevilla@gmail.com",
    email2: "lotuskottayam@gmail.com",
    website: "http://www.riverdalevilla.in/",
    overview: "At Riverdale Villa, a cosy home with three bed rooms, lot of sunshine to soak into, one gets initiated into the curative village experience of the back waters. The surprises include fresh water fishing in the river, canoe rides, the best home cooked Syrian Christian cuisine and the simplicity of an entire village. Riverdale villa is a home stay and the host’s family resides at the same house to provide services to guests. It is very informal, welcoming and open. The house has eco-friendly practices and the guest will be delighted to taste some exclusive home cooked, organic delicacies especially sea food influenced by traditional Travancore cuisine. The duck mappas, prawn grills, hot tapioca pudding, crispy and yummy appams, theeyal, kaalan, chammanthi etc will certainly tickle and take your taste buds to age-old grandma recipes!",
    facilities: "24-hour Room Service, A/c Room, Boating facilities, Cable / Satellite TV, Car hire service, Car parking and valet services, Children's Play Area, Coffee Maker, Coffee shop, Color TV, Conference hall, Conference hall, Cultural Programs, Currency exchange, Doctor-on-call, DVD Player, Exhibition hall, Food, Gift Shop, Group Check-in, Hairdryer, High speed Wi-fi access, Homely Kerala Food, In Room Safe, Internet facility, Iron / Ironing Board, Laptop computers on hire, Laundry, Library, Non A/c Room, North Indian Dishes, Online reservation, Photocopying, Private party area, Refrigerator, Restaurant, Scanning services, Shopping Arcade/ Boutiques, South Indian Dishes, Souvenir Shop, Spa, Swimming Pool, Tour Packages, Translation / interpretation services (on request), Transport and Guide Services, Travel desk, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp, Workstations, Yoga Centre",
    latitude: 9.634555,
    longitude: 76.489135,
  ),
  HomeStay(
    name: "Orchard River Mansion",
    image: "assets/stay/hs-orchard.jpg",
    classification: "Diamond House",
    address: "Pulickakandathil, Pala,\nKottayam, Pin: 686575",
    ph1: "+919447111218",
    ph2: "+919400762025",
    ph3: "",
    email1: "orchardrivermansion@gmail.com",
    email2: "",
    website: "http://orchardrivermansion.com/",
    overview: "Orchard River Mansion Homestay will give you a taste of heaven, and an unforgettable homestay ambiance perched with the river view backyard. Besides providing you with an utterly comfortable stay, it will give you a chance to go through the beauty, the authentic Kerala lifestyle, ethnic food and of course the natural Kerala village life. It is indeed a special place and a perfect holiday spot. It is also a perfect place to host parties at your choice. Be it small family gathering or any social functions (like bachelor parties, wedding night parties, corporate events), we take care of all the arrangements from organizing food, sound, light systems, stage decorations, DJ, security etc.. which gives you stress free days.",
    facilities: "24-hour Room Service, A/c Room, Baby-sitting, Banquet hall, Boating facilities, Cable / Satellite TV, Car parking and valet services, Children's Play Area, Coffee Maker, Color TV, Conference hall, Conference hall, Cultural Programs, Doctor-on-call, Food, Group Check-in, High speed Wi-fi access, Homely Kerala Food, In Room Safe, Internet facility, Iron / Ironing Board, Laptop computers on hire, Laundry, Lounge Bar, MICE (Meetings, Incentives, Conferences & Events), Online reservation, Private party area, Refrigerator, Safe Deposit Lockers, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp",
    latitude: 9.708295,
    longitude: 76.687578,
  ),
  HomeStay(
    name: "Nilasheritagehomestay",
    image: "assets/stay/hs-nilasheritage.jpg",
    classification: " Gold House",
    address: "Vechoor, North of kumarakom,\nKottayam, Pin: 686144",
    ph1: "+919961733009",
    ph2: "",
    ph3: "",
    email1: "krsibu@gmail.com",
    email2: "",
    website: "www.nilasheritagehomestay.com",
    overview: "Newly constructed heritage home stay Near north of kumarakom, Kottayam.",
    facilities: "A/c Room, Cable / Satellite TV, Car parking and valet services, Children's Play Area, Coffee Maker, Color TV, Conference hall, Conference hall, Cultural Programs, Handicap Facilities, Homely Kerala Food, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, Library, Non A/c Room, Refrigerator, Wi-fi Lobby",
    latitude: 9.667536,
    longitude: 76.412135,
  ),
  HomeStay(
    name: "Olickal Home Stay",
    image: "assets/stay/hs-olickal.jpeg",
    classification: "",
    address: "Kanjiramattom-Kavungumpalam Road,\nKanjiramattom , Kottayam, Pin: 686585",
    ph1: "+919061033132",
    ph2: "+914812704285",
    ph3: "",
    email1: "rtolickal@gmail.com",
    email2: "elsolickal@gmail.com",
    website: "",
    overview: "The house is situated in a large pristine farm area 500m away from K. R. Narayanan National Institute of Visual Science and Arts which is a National Film Institute. Aruvikuzhy waterfalls is just 4 km away. Nearest towns are Pala, Ponkunnam, Kanjirappally and Kottayam. St. Alphonsa’s tomb at Bharananganam is just 15 KM away. There are many famous Hindu and Christian pilgrim centres within 3-15 km radius.",
    facilities: "",
    latitude: 9.619599,
    longitude: 76.690836,
  ),
  HomeStay(
    name: "Backwater Heritage",
    image: "assets/stay/hs-backwater.jpg",
    classification: "",
    address: "Kumarakom, Pulikuttissey P. O.\nAymanam, Kottayam, Pin: 686015",
    ph1: "+919745286358",
    ph2: "914812516375",
    ph3: "",
    email1: "mxavierkutty@yahoo.com",
    email2: "",
    website: "www.backwaterheritage.com",
    overview: "Homestay at the Backwater Heritage homestay offers peace, privacy and pure relaxation to the guests. It’s a place to relax and experience loving care and delicious Kerala food. Backwater Heritage homestay is situated away from the rush and heavy traffic of the city. Traditional home made Kerala foods are the main attraction. A haven of peace and serenity, this house made of rose wood and teak overlooks a tributary of the Meenachil River and is located 8 km from Kottayam town. It has a beautiful landscaped garden and comes fully furnished with all modern amenities. The hosts offer mouth-watering less spicy Kerala homemade food or the guests can even cook their own food in the kitchen. The Backwater Heritage home is a most perfect blend of the old world charm and modern amenities. Each day spend in this century old wooden mansion would render one a feeling of serenity, peace and joy, which has been long lost to the frenetic pace of the times that we live in.",
    facilities: "24-hour Room Service, Banquet hall, Boating facilities, Car hire service, Car parking and valet services, Children's Play Area, Conference hall, Doctor-on-call, Facsimile, Laundry, Photocopying, Restaurant",
    latitude: 9.624458,
    longitude: 76.480036,
  ),
    HomeStay(
    name: "Meenakshi Homestay",
    image: "assets/stay/hs-meenakshi.jpg",
    classification: "Gold House",
    address: "Near Bird Sanctuary, Kavanatinkara,\nKumarakom, Kottayam, Pin: 686563",
    ph1: "+919447358356",
    ph2: "+919497226048",
    ph3: "+918075380269",
    email1: "anikoikkalchira@gmail.com",
    email2: "",
    website: "http://kumarakomrooms.com/",
    overview: "Meenakshi Homestay is located at the center of Kumarakom and is just 200 mts away from Kumarakom Bird sanctuary and Taj Hotel. All the rooms have balcony, are fully furnshed and have TV and Wifi. Food is preapred by the host and will be typical Kerala cuisine. Food served will be both vegetarian and non-vegetarian. Book your stay at Meenakshi Lake Cottage today.",
    facilities: "Ayurveda Center, Boating facilities, Car hire service, Car parking and valet services, Travel desk",
    latitude: 9.628188,
    longitude: 76.431871,
  ),
    HomeStay(
    name: "Natureland homestay",
    image: "assets/stay/hs-natureland.jpg",
    classification: "",
    address: "manjadi,Meenadom,\n meenadom, Kottayam, Pin: 686516",
    ph1: "+917592000098",
    ph2: "+914812969098",
    ph3: "",
    email1: "madhumanjadi@gmail.com",
    email2: "naturelandkeralal@gmail.com",
    website: "www.naturelandholidays.com",
    overview: "Natureland Homestay is your home away from home: the perfect place for a pleasant and peaceful stay if you are visiting Kottayam/Kumarakom or Alappuzha (Alleppey). The homestay concept is offered at a very attractive rate to domestic and international tourists of all ages, in a clean, eco friendly and tranquil environment.",
    facilities: "24-hour Room Service, A/c Room, Ayurveda Center, Boating facilities, Cable / Satellite TV, Car parking and valet services, Coffee Maker, Color TV, Cultural Programs, Doctor-on-call, DVD Player, Food, Hairdryer, High speed Wi-fi access, Homely Kerala Food, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, Library, Non A/c Room, North Indian Dishes, Refrigerator, Safe Deposit Lockers, South Indian Dishes, Tour Packages, Travel desk, Wi-fi Lobby, Work Desk with Lamp, Yoga Centre",
    latitude: 9.559760,
    longitude: 76.622960,
  ),
   HomeStay(
    name: "Greenhaven Homestay",
    image: "assets/stay/hs-greenhaven.jpg",
    classification: "Silver House",
    address: "13/188A,Vettathu,Puthuppally,\nKottayam, Pin: 686011",
    ph1: "+919895376346",
    ph2: "+914812464581",
    ph3: "",
    email1: "greenhaven1951@gmail.com",
    email2: "kamalaforasha@gmail.com",
    website: "",
    overview: "Perfect space for both tourists and NRI families from USA, UK, Canada, UAE, and European countries. It is also useful to Pre/Post wedding stays.",
    facilities: "",
    latitude: 9.548660,
    longitude: 76.577895,
  ),
   HomeStay(
    name: "Achadipurahomestay",
    image: "assets/stay/hs-achadipura.jpg",
    classification: "Diamond House",
    address: "Brookside,Paruthumpara, Kuzhimattom P.O,\nKottayam, Kerala, Pin: 686533",
    ph1: "+919822123001",
    ph2: "+919970445066",
    ph3: "",
    email1: "achadipurahomestay@gmail.com",
    email2: "",
    website: "https://www.achadipurahomestay.com/",
    overview: "In the land of letters, latex and lakes is a quaint, traditional space for you to rejuvenate your soul and senses; to experience the original village life in Kottayam or Southern Kerala as a whole. “Achadipura” is over a hundred years old and holds a handful of historic stories and local practices for you to take back after a wonderful vacation. Feel at home with the amazing hosts while being swept into the magical feel of a quiet Kerala countryside.\nThis is a space for you to step away from the rush of urban life and take in a soulful breath of freshness. Cloistered within rows of rubber trees, this traditional home holds a song of the Southern Indian heritage sung in a colonial tune.",
    facilities: "A/c Room, Cable / Satellite TV, Car hire service, Coffee Maker, Color TV, Handicap Facilities, High speed Wi-fi access, Homely Kerala Food, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, Transport and Guide Services, Work Desk with Lamp",
    latitude: 9.528275,
    longitude: 76.538379,
  ),
   HomeStay(
    name: "The Riverside Bliss Stays",
    image: "assets/stay/hs-theriverside.jpg",
    classification: "",
    address: "Yendayar,\nKottayam, Pin: 686514",
    ph1: "+919995492818",
    ph2: "+914828286425",
    ph3: "",
    email1: "contact@theriversidebliss.com",
    email2: "",
    website: "https://theriversidebliss.com",
    overview: "Riverside Bliss stay is located in a village on the foothills of Western Ghats called Yendayar. The place was found and established by a staunch Irish gentleman called John Joseph Murphy during the British rule. We welcome you to the unlost rhythm of pure nature. The property is built in the banks of Manimala River. We have a separate access for getting into the river. The guests are provided with 2 non A/C(not required during monsoons)double rooms. The place is 13 km from its nearest town Mundakayam. Nearest Airport is Cochin. Nearest Railway Station is Kottayam. We provide local sightseeing to beautiful waterfalls and many other things to do. Also we provide tent facility and off-road jeep and bike rides.",
    facilities: "24-hour Room Service, Food, Homely Kerala Food, In Room Safe, Iron / Ironing Board, Laundry, Non A/c Room, Online reservation, South Indian Dishes, Tour Packages, Transport and Guide Services",
    latitude: 9.618080,
    longitude: 76.889654,
  ),
   HomeStay(
    name: "Orchid Holidays",
    image: "assets/stay/hs-orchid.jpg",
    classification: "Gold House",
    address: "Vaikom Road, Kuravilangadu,\nKottayam, Pin: 686633",
    ph1: "+919496159244",
    ph2: "+914822230515",
    ph3: "",
    email1: "info@orchidgroups.in",
    email2: "orchidhomez@gmail.com",
    website: "http://www.orchidgroups.in/",
    overview: "Orchid Holidays offers luxurious stay at affordable prices and a variety of tour packages.",
    facilities: "24-hour Room Service, A/c Room, Beauty saloon, Boating facilities, Cable / Satellite TV, Car hire service, Car parking and valet services, Chinese dishes, Coffee Maker, Color TV, Credit Card Accepted, Currency exchange, Doctor-on-call, DVD Player, Flight status, Food, Hairdryer, High speed Wi-fi access, Homely Kerala Food, In Room Safe, Indoor games, Internet facility, Iron / Ironing Board, Laptop computers on hire, Laundry, North Indian Dishes, Photocopying, Private party area, Refrigerator, Safe Deposit Lockers, South Indian Dishes, Tour Packages, Transport and Guide Services, Weddings in Kerala, Wi-fi Lobby, Work Desk with Lamp",
    latitude: 9.757557,
    longitude: 76.558927,
  ),
   HomeStay(
    name: "Pranayakulam spiritual home",
    image: "assets/stay/hs-pranayakulam.jpg",
    classification: "Silver House",
    address: "Padinjare Vaipel House, Mevelloor,\nKottayam, Pin: 686609",
    ph1: "+918606085104",
    ph2: "+918281580882",
    ph3: "",
    email1: "pranayakulam@gmail.com",
    email2: "livninmoment@gmail.com",
    website: "https://pranayakulam.com/",
    overview: "Kerala village riverside home – stay with loving family, traditional food, training in yoga, meditation and much more.",
    facilities: "A/c Room, Boating facilities, Car parking and valet services, Children's Play Area, Coffee Maker, Color TV, Conference hall, Cultural Programs, Doctor-on-call, Food, High speed Wi-fi access, Homely Kerala Food, Indoor games, Internet facility, Iron / Ironing Board, Laundry, Library, Medical Tourism, Non A/c Room, Online reservation, Refrigerator, South Indian Dishes, Swimming Pool, Tour Packages, Wi-fi Lobby, Work Desk with Lamp, Yoga Centre",
    latitude: 9.842726,
    longitude: 76.457128,
  ),
  HomeStay(
    name: "Green Nestle Heritage Home",
    image: "assets/stay/hs-greennestle.jpg",
    classification: "Gold House",
    address: "Kannachamparambil, Manjoor P. O.\nKuruppanthara, Kottayam, Pin: 686603",
    ph1: "+918078265859",
    ph2: "+919497238215",
    ph3: " +914829242859",
    email1: "greennestlehomes@gmail.com",
    email2: "greennestlehomesusa@gmail.com",
    website: "http://www.greennestlehomes.com/",
    overview: "Unplug and just surrender to nature at Green Nestle Heritage Home. It is accessible by road from Kochi Airport (60 km). A stunning place of amazing hospitality, the homestay is an ideal place to relax and unwind. The food served is simple, home-made and soulful. Staying at Green Nestle is an excellent opportunity to enjoy the real Kerala experience in a fascinating location, with a caring staff to look after you. It is a special place, as it provides something different, especially for those who prefer small, friendly places, and it is the perfect hideaway for the bespoke traveller.",
    facilities: "24-hour Room Service, A/c Room, Baby-sitting, Boating facilities, Cable / Satellite TV, Car parking and valet services, Children's Play Area, Color TV, Cultural Programs, Doctor-on-call, DVD Player, Florist, Food, Gift Shop, Homely Kerala Food, In Room Safe, Internet facility, Iron / Ironing Board, Laundry, Library, Non A/c Room, Private party area, Refrigerator, Safe Deposit Lockers, Shopping Arcade/ Boutiques, South Indian Dishes, Tour Packages, Travel desk, Wi-fi Lobby",
    latitude: 9.740533,
    longitude: 76.515184,
  ),
  HomeStay(
    name: "Vanilla County",
    image: "assets/stay/hs-vanilla.jpg",
    classification: "",
    address: "Mavady Estate Teekoy,\nKottayam, Pin: 686580",
    ph1: "+919744183835,",
    ph2: "+919048624648",
    ph3: "+914822281225",
    email1: "vanillacounty@gmail.com",
    email2: "",
    website: "www.vanillacounty.in",
    overview: "Vanilla County is an authentic and enchanting homestay, in close proximity to the orgin of the Meenachil river at Mavady Hills near Vagamon, Kerala sheltered by rubber trees , various spices, trees and plants.\nThe area comes under the Western Ghats Or Sahyadri Mountain ranges, a proclaimed ' UNESCO ' World Heritage site and is one of the eight hottest hot spots of biological diversity of the world.\nVanilla County is two and half hours drive from Cochin international airport and its unique destination helps travelers understand the true meaning of responsible eco- tourism.\nVanilla County is the perfect take off point for visits to Periyar Wild life Sanctuary, Munnar hill station, Alleppey back waters and Marari beach.",
    facilities: "A/c Room, Credit Card Accepted, Doctor-on-call, Food, Group Check-in, High speed Wi-fi access, Homely Kerala Food, Indoor games, Internet facility, Laundry, Library, Online reservation, Photocopying, Refrigerator, Scanning services, South Indian Dishes, Tour Packages, Transport and Guide Services, Weddings in Kerala, Work Desk with Lamp, Yoga Centre",
    latitude: 9.688531,
    longitude: 76.855537,
  ),
    HomeStay(
    name: "Brookside Heritage Homestay",
    image: "assets/stay/hs-brookside.jpg",
    classification: "Diamond House",
    address: "Kaniamparambil House, Ummacheril Road,\nKumarakom, Kottayam, Pin: 686563",
    ph1: "+919447356139",
    ph2: "+919207736139",
    ph3: "+91 481 2524432",
    email1: "brookside.h.homestay@gmail.com",
    email2: "",
    website: "https://brooksidehomestay.com/",
    overview: "Indulge in a slice of Kumarakom heritage on our property. The Brookside Heritage Homestay or otherwise known to the locals as the Kaniamparambil House is a traditional Syrian Christian mansion built in the year 1915. Crafted by highly skilled artisans, this home can be described as a delicate blend of the wood based Kerala architecture and the brick based British architecture. Surrounded by lush greenery, the serenity of this picturesque abode will never cease to charm you. Situated by the bank of a tributary of the Meenachil River in Kerala, the house is a little recessed from the main road making it an idyllic getaway.",
    facilities: "A/c Room, Cable / Satellite TV, Car hire service, Car parking and valet services, Coffee Maker, Color TV, Doctor-on-call, High speed Wi-fi access, Homely Kerala Food, Internet facility, Online reservation, South Indian Dishes, Wi-fi Lobby",
    latitude: 9.589362,
    longitude: 76.433729,
  ),
    HomeStay(
    name: "Good Shepherd Home Stay",
    image: "assets/stay/hs-goodshepherd.jpg",
    classification: "Gold House",
    address: "1/374B, Chomkara House,\nAmparanirappel P.O, Bharananganam,\nKottayam, Kerala, Pin: 686578",
    ph1: "+919447324217",
    ph2: "+918075621220",
    ph3: "+919074883796",
    email1: "jose.chomkara@gmail.com",
    email2: "bluewarmfoundations@gmail.com",
    website: "https://www.bluewarmfoundations.com/",
    overview: "The variety of experiences that Blue Warm has to offer is simply exciting. The weather is cool most of the time. If you love nature, you've come to the right place. The magic of Blue Warm Foundation is that it is built around the picturesque greenery. You are literally in a room bordering an evergreen surroundings. So imagine wading through jungle streams, taking long walks along country trails that wind through grass, bushes and ancient trees. Join in conversations with colorful wild birds and dance to the rhythm of spectacular butterflies. Blue warm Foundation Pvt.Ltd ,Kerala will be a perfect home stay for you if you want to enjoy with your family and loved ones.",
    facilities: "24-hour Room Service, A/c Room, Banquet hall, Cable / Satellite TV, Car hire service, Car parking and valet services, Children's Play Area, Coffee Maker, Color TV, Conference hall, Conference hall, Cultural Programs, Doctor-on-call, Exhibition hall, Flight status, Food, Gift Shop, Group Check-in, Handicap Facilities, High speed Wi-fi access, Homely Kerala Food, In Room Safe, Indoor games, Internet facility, Iron / Ironing Board, Laundry, Medical Tourism, Meet-and-Greet Services, MICE (Meetings, Incentives, Conferences & Events), North Indian Dishes, Online reservation, Photocopying, Private party area, Refrigerator, Scanning services, South Indian Dishes, Souvenir Shop, Tour Packages, Transport and Guide Services, Travel desk, Video-conferencing facilities & Web casting facilities, Wi-fi Lobby, Work Desk with Lamp",
    latitude: 9.690560,
    longitude: 76.747530,
  ),
];